<?php

$pageData = $this->pageData;

?>
        <div id="MainHeader">
          <h1>Projeto <a href="/finances/project/detail/?id=<?php echo $pageData['projectId']; ?>"><?php echo $pageData['projectTitle']; ?></a></h1>
        </div>
        <div class="TituloForm">
          <h2><?php print $this->translate("#Notify outlay") ?></h2>
          <div><?php print $pageData['outlayDetails'] ?></div>
        </div>
<?php echo $this->form; ?>
