<?php
  $teamMemberData = $this->teamMemberData;
?>
        <div id="MainHeader">
          <h1><?php echo $this->translate("#Remove team member") ?></h1>
        </div>
          <p>
              <?php echo sprintf($this->translate("#Do you confirm removal of team member %s in action %s? This CAN'T be undone."), "<strong>{$teamMemberData['description']}</strong>", "<strong>{$teamMemberData['actionTitle']}</strong>") ?>
          </p>
        <?php echo $this->form; ?>
