<?php
  $pageData = $this->pageData;

?>
<div id="Footer" class="sixteen columns">
	<div class="thirteen columns">IETS &copy; 2013</div>
	<div class="three column right" style="float:right">
<?php
  if ($pageData['loggedIn']) {
?>			<a href="/auth/user/edit/?id=<?php echo $pageData['id']?>"><?php echo $pageData['userName']?></a> | <a href="/auth/user/edit/?id=<?php echo $pageData['id']?>"><?php echo $this->translate("#Edit") ?></a> | <a href="">Sair</a>

<?php
    }

?>
	</div>
    
    <br clear="all" />
    
</div>