<?php
  $pageData = $this->pageData;
  if (is_array($pageData['institutionInfo'])) {
    $institutionInfo = $pageData['institutionInfo'];
?>
        <div id="MainHeader">
          <h1><?php print($institutionInfo['name']) ?></h1>
        </div>
<?php
    if ($pageData['messageToShow']) {
?>
        <div class="flashMessage">
            <?php echo $this->translate($pageData['messageToShow']); ?>
        </div>
<?php
    }
?>
        <div class="Area">
          <h2><?php print($this->translate("#Contacts in this institution")) ?></h2>
          <table class="display dataTable">
            <thead>
              <tr>
                <th>Nome</th>
                <th>Cargo</th>
                <th>Departamento</th>
                <th>&nbsp;</th>
              </tr>
            </thead>
            <tbody>

<?php
/*
 * iterate list and print title
 */

    $linkagesList = $institutionInfo['linkagesList'];
    foreach ($linkagesList as $id => $linkageInfo) {
?>
              <tr>
                <td><a href="/register/contact/detail/?id=<?php print($linkageInfo['contactId']) ?>"><?php print($linkageInfo['contactName']) ?></a></td>
                <td><?php print($linkageInfo['position']) ?></td>
                <td><?php print($linkageInfo['department']) ?></td>
                <td>
                  <a href="#" class="anchorclass" rel="submenu1"><?php echo $this->translate("#Options") ?></a>
                  <div id="submenu1" class="anylinkcss">
                    <ul>
                      <li>
                        <a href="/register/linkage/edit/?id=<?php print($id) ?>"><?php print($this->translate("#Edit")) ?></a>
                      </li>
                      <li>
                        <a href="/projects/index/engagement/?contact=<?php print($linkageInfo['contactId']) ?>"><?php print($this->translate("#Participation in active projects")) ?></a>
                      </li>
                    </ul>
                  </div><!-- #submenu1 -->
                </td>
              </tr>
<?php
    }  // loop iterate list
?>
            </tbody>
          </table>
        </div><!-- .Area -->
<?php
  } else { // else exists institutions list
?>
        <?php print($this->translate("#There is no data about this institution.")) ?>
<?php
  } // end exists institutions list
?>