<?php
$pageData = $this->pageData;
$institutionsList = $pageData['institutionsList'];
?>
<div id="MainHeader">
  <h1>Instituições</h1>
</div>
<?php
/*
 * If exists institutions list
 */
if (is_array($institutionsList)) {
?>

<?php
/*
 * if there is institutions in list
 */
    if (count($institutionsList)) {
?>
            <div class="Area">

              <table class="display dataTable">
            		<thead>
            			<tr>
            				<th width="330">Nome</th>
            				<th width="190">Tipo</th>
            				<th width="190">Cidade</th>
            				<th width="020">UF</th>
            				<th width="070">Relação</th>
            				<th width="070">&nbsp;</th>
            			</tr>
            		</thead>
            		<tbody>
<?php
/*
 * iterate list and print title
 */
        while (list(, $institutionData) = each($institutionsList)) {
?>
                    <td>
                      <?php print($institutionData['name']) ?>
                    </td>
                    <td>
                      <?php print($institutionData['type']) ?>
                    </td>
                    <td>
                      [#CIDADE]
                    </td>
                    <td>
                      [#UF]
                    </td>
                    <td>
                      [#RELAÇÃO]
                    </td>


<?php if (isset($institutionData['editLink'])) { ?>
                    <td>
                      <a class="anchorclass button" rel="submenu1">Opções...</a>
                      <div id="submenu1" class="anylinkcss">
                        <ul>
                          <li>
                            <a href="<?php print($institutionData['editLink']) ?>">Editar</a>
                          </li>
                        </ul>
                      </div><!-- #submenu1 -->
                    </td>
            			</tr>
<?php } ?>
<?php
}  // loop iterate list and print titlei
?>
            		</tbody>
            	</table><br />
<?php
    } else { // end else there is institutions in list
?>
          <div class="Area">
          <h2>Instituições</h2>
    <?php print("<p>Não há instituições cadastradas.</p>") ?>

<?php
    } // end else there is institutions in list
?>
<?php
} else { // else exists institutions list
?>
    <?php print("Não existe lista de instituições cadastradas.") ?>

    <?php
} // end exists institutions list
?>
            <p>
              <a href="<?php print($this->createInstitutionLink) ?>" class="button three columns alpha omega">Criar Nova Instituição</a>
            </p>
          </div><!-- Area -->
