<?php
/*
 * If exists contacts list
 */
if (is_array($this->contactInfo)) {
    $contactData = $this->contactInfo;
?>
<div id="MainHeader">
  <h1>Contato: <?php print($contactData['name']) ?></h1>
</div>


<div class="Area">
  <div class="three columns Right alpha">
    <p>
      Nome:
    </p>
  </div>
  <div class="five columns">
    <p>
      <?php print($contactData['name']) ?>
    </p>
  </div>
  <div class="two columns Right">
    <p>
      Relação com o Iets:
    </p>
  </div>
  <div class="four columns omega">
    <p>
      [#Relação]
    </p>
  </div>
</div><!-- .Area -->

<?php
/*
 * iterate list and print title
 */

    $phoneNumbersList = $contactData['phoneData'];

    if (count($phoneNumbersList) > 0) {

?>
          <div class="Area">
            <h2>Telefones</h2>
            <table id="Telefones" class="display dataTable">
              <thead>
                <tr>
                  <th width="20">DDD</th>
                  <th width="100">Número</th>
                  <th width="220">Tipo</th>
                  <th width="1%">&nbsp;</th>
                </tr>
              </thead>
              <tbody>

<?php
    foreach ($phoneNumbersList as $phoneId => $phoneInfo) {
?>
                <tr>
                  <td>
<?php if (isset($phoneInfo['area_code']) && ($phoneInfo['area_code'] != "")) { ?>
(<?php print($phoneInfo['area_code']) ?>)
<?php } else { print '&nbsp;'; }?>
                  </td>
                  <td>
<?php if (isset($phoneInfo['local_number']) && ($phoneInfo['local_number'] != "")) { ?>
<?php print($phoneInfo['local_number']) ?>
<?php } else { print '&nbsp;'; }?>
                  </td>
                  <td>
<?php if (isset($phoneInfo['label'])) { ?>
<?php print($phoneInfo['label']) ?>
<?php } else { print '&nbsp;'; }?>
                  </td>
                  <td>
                    <a class="anchorclass button" rel="submenu1">Opções...</a> 
                    <div id="submenu1" class="anylinkcss">
                        <ul>
                          <li>
                            <a href="/register/contact/change-phone-number/?id=<?php print($phoneId); ?>">Editar</a>
                          </li>
                        </ul>
                    </div><!-- #submenu1 -->
                  </td>
                </tr>
<?php
}  // loop iterate list and print titlei
?>
              </tbody>
            </table>
          </div><!-- .Area -->
<?php } ?>

            <p>
              <a href="/register/contact/add-phone-number/?id=<?php print($this->contactInfo['id']) ?>" class="button three columns alpha omega">Adicionar telefone</a>
            </p>

<?php
/*
 * iterate list and print title
 */

    $linkagesList = $contactData['linkagesList'];

    if (count($linkagesList) > 0) {

?>
          <div class="Area">
            <h2>Vínculos</h2>
            <table id="Telefones" class="display dataTable">
              <thead>
                <tr>
                  <th width="220">Instituição</th>
                  <th width="80">Departamento</th>
                  <th width="100">Posição</th>
                  <th width="1%">&nbsp;</th>
                </tr>
              </thead>
              <tbody>
<?php
    while (list(, $linkageInfo) = each($linkagesList)) {
?>
                <tr>
                  <td>
<?php if (isset($linkageInfo['institutionEdit'])) { ?>
<a href="<?php print($linkageInfo['institutionEdit']) ?>"><?php print($linkageInfo['institutionName']) ?></a>
<?php } else { print '&nbsp;'; }?>
                  </td>
                  <td>
<?php if (isset($linkageInfo['department']) && ($linkageInfo['department'] != "")) { ?>
<?php print($linkageInfo['department']) ?>
<?php } else { print '&nbsp;'; }?>
                  </td>
                  <td>
<?php if (isset($linkageInfo['position']) && ($linkageInfo['position'] != "")) { ?>
<?php print($linkageInfo['position']) ?>
<?php } else { print '&nbsp;'; }?>
                  </td>
                  <td>
                    <a class="anchorclass button" rel="submenu1">Opções...</a> 
                    <div id="submenu1" class="anylinkcss">
                        <ul>
                          <li>
                            <a href="/register/linkage/edit/?id=<?php print($linkageInfo['id']); ?>">Editar</a>
                          </li>
                        </ul>
                    </div><!-- #submenu1 -->
                  </td>
                </tr>
<?php
}  // loop iterate list and print titlei
?>
              </tbody>
            </table>
<?php } ?>
            <p>
              <a href="<?php print($this->contactInfo['linkLinkageCreate']) ?>" class="button three columns alpha omega">Criar Novo Vínculo</a>
            </p>
          </div><!-- Area -->
<?php
} else { // else exists contacts list
?>
          <div class="Area">
    <?php print("Não há informações sobre este contato.") ?>
          </div><!-- Area -->

    <?php
} // end exists contacts list
?>
