<?php
$pageData = $this->pageData;

if (is_array($pageData['contactInfo'])) {
    $contactInfo = $pageData['contactInfo'];
?>
<div id="MainHeader">
  <h1>Contato: <?php print($contactInfo['name']) ?></h1>
</div>


<div class="Area">
  <div class="three columns Right alpha">
    <p>
      Nome:
    </p>
  </div>
  <div class="five columns">
    <p>
      <?php print($contactInfo['name']) ?>
    </p>
  </div>
  <div class="two columns Right">
    <p>
      Relação com o Iets:
    </p>
  </div>
  <div class="four columns omega">
    <p>
      <?php print($contactInfo['relationship']) ?>
    </p>
  </div>
</div><!-- .Area -->

          <div class="Area">
<?php

    $phonesList = $pageData['phonesList'];

    if (count($phonesList) > 0) {

?>
            <h2>Telefones</h2>
            <table id="Telefones" class="display dataTable">
              <thead>
                <tr>
                  <th width="20">DDD</th>
                  <th width="100">Número</th>
                  <th width="220">Tipo</th>
                  <th width="1%">&nbsp;</th>
                </tr>
              </thead>
              <tbody>

<?php
    foreach ($phonesList as $phoneId => $phoneInfo) {
?>
                <tr>
                  <td>
<?php if (isset($phoneInfo['areaCode']) && ($phoneInfo['areaCode'] != "")) { ?>
(<?php print($phoneInfo['areaCode']) ?>)
<?php } else { ?>&nbsp;<? } ?>
                  </td>
                  <td>
<?php if (isset($phoneInfo['localNumber']) && ($phoneInfo['localNumber'] != "")) { ?>
<?php print($phoneInfo['localNumber']) ?>
<?php } else { ?>&nbsp;<? } ?>
                  </td>
                  <td>
<?php if (isset($phoneInfo['label'])) { ?>
<?php print($phoneInfo['label']) ?>
<?php } else { ?>&nbsp;<? } ?>
                  </td>
                  <td>
                    <a class="anchorclass button" rel="submenu1">Opções...</a>
                    <div id="submenu1" class="anylinkcss">
                        <ul>
                          <li>
                            <a href="/register/contact/change-phone-number/?phone=<?php print($phoneId); ?>">Editar</a>
                          </li>
                        </ul>
                    </div><!-- #submenu1 -->
                  </td>
                </tr>
<?php
}  // loop iterate list and print titlei
?>
              </tbody>
            </table>
<?php } ?>

            <p>
              <a href="/register/contact/add-phone-number/?contact=<?php print($this->contactInfo['id']) ?>" class="button three columns alpha omega">Adicionar telefone</a>
            </p>
          </div><!-- .Area -->





          <div class="Area">
<?php

    $emailsList = $pageData['emailsList'];

    if (count($emailsList) > 0) {

?>
            <h2>Emails</h2>
            <table id="Emails" class="display dataTable">
              <thead>
                <tr>
                  <th width="100">Endere&ccedil;o</th>
                  <th width="220">Tipo</th>
                  <th width="1%">&nbsp;</th>
                </tr>
              </thead>
              <tbody>

<?php
    foreach ($emailsList as $emailId => $emailInfo) {
?>
                <tr>
                  <td>
<?php if (isset($emailInfo['address']) && ($emailInfo['address'] != "")) { ?>
<?php print($emailInfo['address']) ?>
<?php } else { ?>&nbsp;<? } ?>
                  </td>
                  <td>
<?php if (isset($emailInfo['label'])) { ?>
<?php print($emailInfo['label']) ?>
<?php } else { ?>&nbsp;<? } ?>
                  </td>
                  <td>
                    <a class="anchorclass button" rel="submenu1">Opções...</a>
                    <div id="submenu1" class="anylinkcss">
                        <ul>
                          <li>
                            <a href="/register/contact/change-email/?email=<?php print($emailId); ?>">Editar</a>
                          </li>
                        </ul>
                    </div><!-- #submenu1 -->
                  </td>
                </tr>
<?php
}  // loop iterate list and print titlei
?>
              </tbody>
            </table>
<?php } ?>

            <p>
              <a href="/register/contact/add-email/?contact=<?php print($this->contactInfo['id']) ?>" class="button three columns alpha omega">Adicionar email</a>
            </p>
          </div><!-- .Area -->




          <div class="Area">
<?php

    $messengersList = $pageData['messengersList'];

    if (count($messengersList) > 0) {

?>
            <h2>Serviços de Mensagens</h2>
            <table id="Messengers" class="display dataTable">
              <thead>
                <tr>
                  <th width="100">Servi&ccedil;o</th>
                  <th width="220">Conta</th>
                  <th width="1%">&nbsp;</th>
                </tr>
              </thead>
              <tbody>

<?php
    foreach ($messengersList as $messengerId => $messengerInfo) {
?>
                <tr>
                  <td>
<?php if (isset($messengerInfo['service'])) { ?>
<?php print($messengerInfo['service']) ?>
<?php } else { ?>&nbsp;<? } ?>
                  </td>
                  <td>
<?php if (isset($messengerInfo['address']) && ($messengerInfo['address'] != "")) { ?>
<?php print($messengerInfo['address']) ?>
<?php } else { ?>&nbsp;<? } ?>
                  </td>
                  <td>
                    <a class="anchorclass button" rel="submenu1">Opções...</a>
                    <div id="submenu1" class="anylinkcss">
                        <ul>
                          <li>
                            <a href="/register/contact/change-messenger/?messenger=<?php print($messengerId); ?>">Editar</a>
                          </li>
                        </ul>
                    </div><!-- #submenu1 -->
                  </td>
                </tr>
<?php
}  // loop iterate list and print titlei
?>
              </tbody>
            </table>
<?php } ?>

            <p>
              <a href="/register/contact/add-messenger/?contact=<?php print($this->contactInfo['id']) ?>" class="button three columns alpha omega">Adicionar serviço</a>
            </p>
          </div><!-- .Area -->
          <div class="Area">
<?php
/*
 * iterate list and print title
 */

    $linkagesList = $pageData['linkagesList'];

    if (count($linkagesList) > 0) {

?>
          <div class="Area">
            <h2>Vínculos</h2>
            <table id="Telefones" class="display dataTable">
              <thead>
                <tr>
                  <th width="220">Instituição</th>
                  <th width="80">Departamento</th>
                  <th width="100">Posição</th>
                  <th width="1%">&nbsp;</th>
                </tr>
              </thead>
              <tbody>
<?php
    foreach($linkagesList as $linkageId => $linkageInfo){
?>
                <tr>
                  <td>
<?php if (isset($linkageInfo['institutionName'])) { ?>
<a href="/register/institution/edit/?id=<?php print($linkageId) ?>"><?php print($linkageInfo['institutionName']) ?></a>
<?php } else { ?>&nbsp;<? } ?>
                  </td>
                  <td>
<?php if (isset($linkageInfo['department']) && ($linkageInfo['department'] != "")) { ?>
<?php print($linkageInfo['department']) ?>
<?php } else { ?>&nbsp;<? } ?>
                  </td>
                  <td>
<?php if (isset($linkageInfo['position']) && ($linkageInfo['position'] != "")) { ?>
<?php print($linkageInfo['position']) ?>
<?php } else { ?>&nbsp;<? } ?>
                  </td>
                  <td>
                    <a class="anchorclass button" rel="submenu1">Opções...</a>
                    <div id="submenu1" class="anylinkcss">
                        <ul>
                          <li>
                            <a href="/register/linkage/edit/?id=<?php print($linkageId); ?>">Editar</a>
                          </li>
                        </ul>
                    </div><!-- #submenu1 -->
                  </td>
                </tr>
<?php
}  // loop iterate list and print titlei
?>
              </tbody>
            </table>
<?php } ?>
            <p>
              <a href="/register/linkage/create/?contact=<?php print($this->contactInfo['id']) ?>" class="button three columns alpha omega">Criar Novo Vínculo</a>
            </p>
          </div><!-- Area -->
<?php
} else { // else exists contacts list
?>
          <div class="Area">
    <?php print("Não há informações sobre este contato.") ?>
          </div><!-- Area -->

    <?php
} // end exists contacts list
?>