<?php
  $pageData = $this->pageData;
  $contactData = $pageData['contactData'];
?>
        <div id="MainHeader">
          <h1><?php echo $this->translate("#Edit contact") ?></h1>
        </div>
<?php echo $this->form; ?>
          <p>
            <a href="/register/linkage/create/?contact=<?php print($contactData["id"]); ?>" class="button three columns alpha omega"><?php echo $this->translate("#Create linkage") ?></a>
          </p>

        