<div id="MainHeader">
  <h1>Contatos</h1>
</div>
<?php 
/*
 * If exists contacts list
 */
if (is_array($this->contactsList)) {
?>

<?php 
/*
 * if there is contacts in list
 */
    if (count($this->contactsList)) {
?>
            <div class="Area">
              <table class="display dataTable">
            		<thead>
            			<tr>
            				<th width="330">Nome</th>
            				<th width="070">&nbsp;</th>
            			</tr>
            		</thead>
            		<tbody>
<?php 
/*
 * iterate list and print title
 */
        while (list(, $contactData) = each($this->contactsList)) {
?>
            			<tr>
            				<td><a href="<?php print($contactData['linkDetail']) ?>"><?php print($contactData['name']) ?></a></td>
<?php if (isset($contactData['editLink'])) { ?>
                    <td>
                      <a href="#" class="anchorclass" rel="submenu1">Opções</a> 
                      <div id="submenu1" class="anylinkcss">
                        <ul>
                          <li>
                            <a href="<?php print($contactData['editLink']) ?>">Editar</a>
                          </li>
                        </ul>
                      </div><!-- #submenu1 -->
                    </td> 
            			</tr>
<?php } ?>
<?php
}  // loop iterate list and print titlei
?>
            		</tbody>
            	</table><br>
<?php
    } else { // end else there is contacts in list
?>
          <div class="Area">
          <h2>Instituições</h2>
    <?php print("Não há contatos cadastrados.") ?>
    
<?php
    } // end else there is contacts in list
?>
<?php
} else { // else exists contacts list 
?>
    <?php print("Não existe lista de contatos cadastrados.") ?>

    <?php
} // end exists contacts list
?>
            <p>
              <a href="<?php print($this->createContactLink) ?>" class="button three columns alpha omega">Criar Novo Contato</a>
            </p>
          </div><!-- Area -->  
