<?php
$pageData = $this->pageData;
$contactsList = $pageData['contactsList'];
?>
<div id="MainHeader">
  <h1><?php echo $this->translate("#Contacts") ?></h1>
</div>
<?php
/*
 * If exists contacts list
 */
if (is_array($contactsList)) {
?>

<?php
/*
 * if there is contacts in list
 */
    if (count($contactsList)) {
?>
            <div class="Area">
              <table class="display dataTable">
            		<thead>
            			<tr>
            				<th width="330"><?php echo $this->translate("#Name") ?></th>
            				<th width="070">&nbsp;</th>
            			</tr>
            		</thead>
            		<tbody>
<?php
/*
 * iterate list and print title
 */
        foreach  ($contactsList as $contactId => $contactData) {
?>
            			<tr>
            				<td><a href="/register/contact/detail/?id=<?php print($contactId) ?>"><?php print($contactData['name']) ?></a></td>
<?php if (isset($contactData['editLink'])) { ?>
                    <td>
                      <a class="anchorclass button" rel="submenu1"><?php echo $this->translate("#Options...") ?></a>
                      <div id="submenu1" class="anylinkcss">
                        <ul>
                          <li>
                            <a href="/register/contact/edit/?id=<?php print($contactId) ?>"><?php echo $this->translate("#Edit") ?></a>
                          </li>
                        </ul>
                      </div><!-- #submenu1 -->
                    </td>
            			</tr>
<?php } ?>
<?php
}  // loop iterate list and print titlei
?>
            		</tbody>
            	</table>
            </div>
            <br>
<?php
    } else { // end else there is contacts in list
?>
          <div class="Area">
          <h2><?php echo $this->translate("#No registered contacts") ?></h2>
          </div>


<?php
    } // end else there is contacts in list
?>
<?php
} else { // else exists contacts list
?>
    <?php echo $this->translate("#Contacts list was not found") ?>
    <?php
} // end exists contacts list
?>
            <p>
              <a href="/register/contact/create" class="button three columns alpha omega"><?php echo $this->translate("#Add new contact") ?></a>
            </p>
          </div><!-- Area -->
