<?php
  $contactData = $this->contactData;
?>
        <div id="MainHeader">
          <h1><?php echo $this->translate("#Remove contact") ?></h1>
        </div>
          <p>
              <?php echo sprintf($this->translate("#Confirm removal of contact %s. This CAN'T be undone."), $contactData['name']) ?>
          </p>
        <?php echo $this->form; ?>
          <p>
            <a href="/register/contact" class="button three columns alpha omega"><?php echo $this->translate("#Not remove") ?></a>
          </p>