<?php
  if (is_array($this->viewInfo)) {
    $viewInfo = $this->viewInfo;
?>
        <div id="MainHeader">
          <h1><a href="<?php echo $viewInfo['linkProjectDetail']; ?>"><?php echo $viewInfo['projectTitle']; ?></a></h1>
        </div>
        
        <div class="Area">
          <h2>Novo pagamento</h2>
          <div class="three columns Right alpha">
            Ação:
          </div>
          <div class="six columns">
            <a href="<?php echo $viewInfo['linkActionDetail']; ?>"><?php echo $viewInfo['actionTitle']; ?></a>
          </div>
<?php 
    if (isset($viewInfo['contactName'])) {
?>
          <div class="one column Right">
            Recurso:
          </div>
          <div class="four columns omega">
            <a href="<?php echo $viewInfo['linkContactDetail']; ?>"><?php echo $viewInfo['contactName']; ?></a>
          </div>
<?php
    } else {
?>
          <div class="five columns omega">
            &nbsp;
          </div>
<?php
    }
?>
        </div><!-- .Area -->
<?php
  }
?>
<?php echo $this->form; ?>