        <div id="MainHeader">
          <!-- <h1>Projeto <a href="<?php echo $viewInfo['linkProjectDetail']; ?>"><?php echo $viewInfo['projectTitle']; ?></a></h1> -->
          <h1>Projeto <a href="#">Nome do Projeto</a></h1>
        </div>
      <div class="TituloForm">
        <h2>Editar Desembolso</h2>

        <div class="three columns Right alpha">
          Ação:
        </div>
        <div class="six columns">
          <!-- <a href="<?php echo $viewInfo['linkActionDetail']; ?>"><?php echo $viewInfo['actionTitle']; ?></a> -->
          <a href="#">Nome da ação</a>
        </div>
        <div class="one column Right">
          Recurso:
        </div>
        <div class="four columns omega">
          <!-- <a href="<?php echo $viewInfo['linkContactDetail']; ?>"><?php echo $viewInfo['contactName']; ?></a> -->
          <a href="#">Nome do contato</a>
        </div>
      </div>
<?php echo $this->form; ?>