<?php
  $pageData = $this->pageData;
  $receivableData = $pageData['receivableData'];
  $productsList = $receivableData['requiredProducts'];
?>
<script type="text/javascript">

$(document).ready(function(){

    $("#newProductDiv").hide();

    $('#newProductButton').click(function(){
        $.ajax({
            type: 'get',
            data: 'requirementForReceiving=<?php print $receivableData['id'] ?>',
            url:'/projects/product/lean-create',
            success: function(successReturn){
            $('#newProductDiv').html(successReturn);
            }
        })


         $("#newProductDiv").slideToggle();
    });
    $('#hideNewProductHref').click(function(){
         $("#newProductDiv").slideToggle();
    });

});

    function callProductLeanCreate(id){

        $.ajax({
            type: 'get',
            data: 'requirementForReceiving=' + id,
            url:'/projects/product/lean-create',
            success: function(successReturn){
            $('#newProductFormDiv').html(successReturn);
            }
        })

         $("#newProductDiv").slideToggle();
         $("#responsibleButton").hide();
    }

</script>

        <div id="MainHeader">
          <h1><span class="weight_normal"><?php print($this->translate("#Project")); ?></span> <a href="/finances/project/detail/?id=<?php print($receivableData['projectId']) ?>"><?php print($receivableData['projectTitle']) ?></a></h1>
        </div><!-- MainHeader -->
<?php
    if ($receivableData['messageToShow']) {
?>
        <div class="flashMessage">
            <?php echo $this->translate($receivableData['messageToShow']); ?>
        </div>
<?php
    }
?>
        <div class="TituloForm">
          <h2><?php print(sprintf($this->translate("#Details of receivable %s"), $receivableData['title'])); ?></h2>
            <a class="button" href="/finances/receivable/edit/?id=<?php echo $receivableData['id'] ?>"><img src="/images/icon_edit.png" align="middle" /> <?php echo $this->translate("#Edit receivable") ?></a>
            <a class="button" href="/finances/receivable/notify/?id=<?php echo $receivableData['id'] ?>"><img src="/images/icon_calendar.png" align="middle" /> <?php echo $this->translate("#Notify receiving") ?></a>
            <a class="button" id="newProductButton" href="#"><img src="/images/icon_create.png" align="middle" /><?php echo $this->translate("#Create new product") ?></a>
            <a class="button" href=""><img src="/images/icon_create.png" align="middle" /><?php echo $this->translate("#Add existent product") ?></a>
        </div>
          <div id="newProductDiv" class="slidingDiv">
              <h3>   <?php print($this->translate("#Inform new product!!!")); ?>  </h3>
              <div id="newProductFormDiv">&nbsp;</div>

            <br class="clear"/>
            <a class="alpha" href="#newProduct" id="newProductHref"><?php print($this->translate("#Hide form")); ?></a>
          </div>
        <div class="AreaInfo">
          <div class="two columns">
            <span class="label"><?php print($this->translate("#Description:")); ?>:</span>
          </div>
          <div class="twelve columns">
            <?php print($receivableData['description']); ?>
          </div>
          <div class="three columns">
            <span class="label"><?php print($this->translate("#Predicted receiving:")); ?></span>
          </div>
          <div class="three columns">
            <?php print($receivableData['predictedDate']); ?>
          </div>
          <div class="two columns">
            <span class="label"><?php print($this->translate("#Predicted value:")); ?></span>
          </div>
          <div class="three columns">
            <?php print($receivableData['predictedValue']); ?>
          </div>

<?php
if (!is_null($receivableData['deliveryDate'])) {
?>
          <div class="two columns">
            <span class="label"><?php print($this->translate("#Delivery Date:")); ?>:</span>
          </div>
          <div class="two columns">
            <?php print($receivableData['deliveryDate']); ?>
          </div>
<?php
}
?>
		  <br clear="all" />
          <div class="three columns">
            <span class="label"><?php print($this->translate("#Date received:")); ?></span>
          </div>
          <div class="three columns">
            <?php print($receivableData['realDate']); ?>
          </div>
          <div class="two columns">
            <span class="label"><?php print($this->translate("#Real Value:")); ?></span>
          </div>
          <div class="three columns">
            <?php print($receivableData['realValue']); ?>
          </div>
           <br clear="all" />
        </div><!-- .Area -->
        <div id="tabs">
          <ul>
            <li><a href="#tabs-products"><?php echo $this->translate("#Products") ?></a></li>
          </ul>
          <div id="tabs-products">
            <table id="SubAcoes" class="display dataTable">
              <thead>
                <tr>
                  <th width="200"><?php print($this->translate("#Product")); ?></th>
                  <th width="100"><?php print($this->translate("#Responsible")); ?></th>
                  <th width="100"><?php print($this->translate("#Status")); ?></th>
                  <th width="10">&nbsp;</th>
                </tr>
              </thead>
              <tbody>
<?php
  $requiredProducts = $receivableData['requiredProducts'];
  foreach ($requiredProducts as $id => $actionData) {
?>
                <tr>
                  <td><a href="/projects/action/detail/?id=<?php print($id);?>"><?php print($actionData['title']) ?></a></td>
                  <td><?php print($actionData['responsibleName']); ?></td>
                  <td><?php print($this->translate($actionData['status'])); ?></td>
                      <td>
                    <a href="#" class="button one column alpha omega anchorclass" rel="submenu1"><?php print($this->translate("#Options")); ?></a>
                    <div id="submenu1" class="anylinkcss">
                        <ul>
                          <li>
                            <a href="/projects/action/edit/?id=<?php print($id);?>"><?php print($this->translate("#Edit")); ?></a>
                          </li>
                        </ul>
                    </div><!-- #submenu1 -->
                  </td>
                </tr>
<?php
  }
?>
              </tbody>
            </table>
          </div><!-- #tabs-products -->
        </div><!-- #tabs -->
