<?php
  $pageData = $this->pageData;
  $projectsList = $pageData['projectsList'];

?>
        <div id="MainHeader">
          <h1><?php echo $this->translate("#Active Projects") ?></h1>
        </div>
<?php
  /*
   * If exists projects list
   */
  if (is_array($projectsList)) {
?>
<?php
    /*
     * if there is projects in list
     */
    if (count($projectsList)) {
?>
        <div class="Area">
           <table class="display dataTable">
              <thead>
                  <tr>
                      <th width="200"><?php echo $this->translate("#Project") ?></th>
                      <th width="100"><?php echo $this->translate("#Client") ?></th>
                      <th width="100"><?php echo $this->translate("#Delivery date") ?></th>
                      <th width="100"><?php echo $this->translate("#Value") ?></th>
                      <th width="150"><?php echo $this->translate("#Product") ?></th>
                      <th width="1%">&nbsp;</th>
                  </tr>
              </thead>
              <tbody>
<?php
      /*
       * iterate list and print title
       */
      foreach ($projectsList as $projectId => $projectData) {
          $projectName = $projectData['projectName'];
          $clientName = $projectData['clientName'];
          $receivablesList = $projectData['receivablesList'];
          foreach ($receivablesList as $receivableId => $receivableData) {
            $deliveryDate = $receivableData['deliveryDate'];
            $differenceInDays = $receivableData['differenceInDays'];
            $receivableValue = $receivableData['receivableValue'];
            $productsList = $receivableData['productsList'];
            foreach ($productsList as $productId => $productData) {
?>
                <tr>
                  <td><a href="/projects/project/detail/?id=<?php $projectId ?>"><?php print($projectName) ?></a></td>
                  <td><?php print($projectData['clientName']) ?></td>
                  <td><?php print($deliveryDate) ?> (<?php print($differenceInDays) ?>)</td>
                  <td><?php print($receivableValue) ?></td>
                  <td><?php print($productData['productName']) ?></td>
                  <td>
                      <a class="anchorclass button" rel="submenu1"><?php echo $this->translate("#Options...") ?></a>
                      <div id="submenu1" class="anylinkcss">
                          <ul>
                          <li>
                              <a href="/projects/action/detail/?id=<?php print($productId) ?>"><?php echo $this->translate("#Detail") ?></a>
                          </li>
                          </ul>
                      </div><!-- #submenu1 -->
                  </td>
                </tr>
<?php
                $deliveryDate = "--/--/----";
                $differenceInDays = "&nbsp;";
                $receivableValue = "-.--";
                $projectName = "&nbsp;";
                $clientName = "&nbsp;";
            }

          }
      }  // loop iterate list and print titlei
?>
          		</tbody>
          	</table>
<?php
    } else { // end else there is projects in list
?>
          <div class="Area">
            <h2>Projetos</h2>
            <?php print("<p>Não há projetos cadastrados.</p>") ?>

<?php
    } // end else there is projects in list
?>
<?php
  } else { // else exists projects list
?>
            <?php print($this->translate("#There is no list of projects.")) ?>
<?php
  } // end exists projects list
?>
            <p>
              <a href="/projects/project/create" class="button three columns alpha omega"><?php echo $this->translate("#Create New Project") ?></a>
            </p>
          </div><!-- Area -->
