<?php
  $pageData = $this->pageData;
  $projectsList = $pageData['projectsList'];

?>
        <div id="MainHeader">
          <h1><?php echo $this->translate("#Active Projects") ?></h1>
        </div>
        <div class="Area">
<?php
  /*
   * If exists projects list
   */
  if (is_array($projectsList)) {
?>
<?php
    /*
     * if there is projects in list
     */
    if (count($projectsList)) {
?>

                <h2><?php echo $this->translate("#Active projects") ?></h2>
                <a href="javascript:$('.treeTable').expandAll();"><?php echo $this->translate("#Expand all") ?></a> | <a href="javascript:$('.treeTable').collapseAll();"><?php echo $this->translate("#Collapse all") ?></a>
                <table id="tree" border="1">
                    <thead>
                            <tr>
                            <th width="150"><?php echo $this->translate("#Project") ?></th>
                            <th width="100"><?php echo $this->translate("#Client") ?></th>
                            <th width="100"><?php echo $this->translate("#Delivery date") ?></th>
                            <th width="100"><?php echo $this->translate("#Value") ?></th>
                            </tr>
                    </thead>
                    <tbody>
    <?php

      foreach ($projectsList as $projectId => $projectData) {
          $projectName = $projectData['projectName'];
          $clientName = $projectData['clientName'];
          $receivablesList = $projectData['receivablesList'];
          $projectNodeId = "project-" . $projectId;
?>
                    <tr id="node-<?php print ($projectNodeId) ?>">
                    <td><a href='/projects/project/detail/?id=<?php print($projectId) ?>'><?php print ($projectName) ?></a></td>
                    <td><?php print($clientName) ?></td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    </tr>

<?php
    $receivableCounter = 0;
    foreach ($receivablesList as $receivableId => $receivableData) {
        $deliveryDate = $receivableData['deliveryDate'];
        $differenceInDays = $receivableData['differenceInDays'];
        $receivableValue = $receivableData['receivableValue'];
        $productsList = $receivableData['productsList'];
        $classId = "child-of-node-$projectNodeId";
        $receivableNodeId = "receivable-$receivableId";
        $receivableCounter++;
        $parcelLabel = $receivableData['receivableTitle'];
?>
                    <tr id="node-<?php print ($receivableNodeId) ?>" class="<?php print ($classId) ?>">
                    <td><?php print($parcelLabel) ?></td>
                    <td>&nbsp;</td>
                    <td><?php print($deliveryDate) ?>&nbsp;<?php print($differenceInDays) ?></td>
                    <td><?php print($receivableValue) ?></td>
                    </tr>

<?php
            foreach ($productsList as $productId => $productData) {
                $productNodeId = "product-" . $productId;
                $classId = "child-of-node-$receivableNodeId";
    ?>
                    <tr id="node-<?php print ($productNodeId) ?>" class="<?php print ($classId) ?>">
                    <td><?php print($productData['productName']) ?></td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    </tr>
    <?php
            }
        }
      }
    ?>
            <!-- # Fim do loop -->
                </tbody>
                </table>
                <br />

<?php
    }
  } else { // else exists projects list
?>
            <?php print($this->translate("#There is no list of projects.")) ?>
<?php
  } // end exists projects list
?>
          </div><!-- Area -->
