<?php
  $outsideServiceData = $this->outsideServiceData;
?>
        <div id="MainHeader">
          <h1><?php echo $this->translate("#Remove outside service") ?></h1>
        </div>
          <p>
              <?php echo sprintf($this->translate("#Do you confirm removal of outside service %s in action %s? This CAN'T be undone."), "<strong>{$outsideServiceData['description']}</strong>", "<strong>{$outsideServiceData['actionTitle']}</strong>") ?>
          </p>
        <?php echo $this->form; ?>
