          <script type="text/javascript">
            function populateResponsibleAtSupplier() {
              var id = $('#institution').val();

              $.getJSON('/resources/material-supply/populate-responsible-at-supplier/?id=' + id, function(data) {
                var html = '';
                var len = data.length;
                html += '<option value="0">(escolha uma pessoa)</option>';
                for (var i = 0; i< len; i++) {
                  html += '<option value="' + data[i].id + '">' + data[i].title + '</option>';
                }
                $('#linkage').empty();
                $('#linkage').append(html);
              });
            }
          </script>
<?php
  $pageData = $this->pageData;
?>
        <div id="MainHeader">
          <h1><?php print($this->translate('#Project')) ?> <?php print($pageData['projectTitle']) ?></h1>
        </div>
        <div class="TituloForm">
          <h2><?php print($this->translate('#New material supply for action')) ?> <a href='/projects/action/detail/?id=<?php print($pageData['actionId']) ?>'><?php echo $pageData['actionTitle']; ?></a></h2>
        </div>
<?php echo $this->form; ?>