<?php
  $pageData = $this->pageData;
?>
          <script type="text/javascript">
            function populateResponsibleAtSupplier() {
              var id = $('#institution').val();

              $.getJSON('/resources/material-supply/populate-responsible-at-supplier/?id=' + id, function(data) {
                var html = '';
                var len = data.length;
                html += '<option value="0">(escolha uma pessoa)</option>';
                for (var i = 0; i< len; i++) {
                  html += '<option value="' + data[i].id + '">' + data[i].title + '</option>';
                }
                $('#linkage').empty();
                $('#linkage').append(html);
              });
            }
          </script>
        <div id="MainHeader">
          <h1><?php print($this->translate('#Edit material supply')); ?></h1>
        </div>
        <div class="TituloForm">
          <h2><?php print($this->translate('#Action:')); ?> <a href="/projects/action/detail/?id=<?php echo $pageData['actionId']; ?>"><?php echo $pageData['actionTitle']; ?></a></h2>
        </div>
<?php echo $this->form; ?>