<script type="text/javascript">

function populateResponsibleAtClient()
{
var id = $('#client').val();

$.getJSON('/projects/project/populate-responsible-at-client/?id=' + id, function(data){
    var html = '';
    var len = data.length;
    for (var i = 0; i< len; i++) {
        html += '<option value="' + data[i].id + '">' + data[i].title + '</option>';
    }
    $('#responsibleAtClient').append(html);
});

}


</script>
<div id="MainHeader">
      <h1><?php print($this->translate('#Create project')) ?></h1>
    </div>
<?php echo $this->form; ?>
