<?php

$pageData = $this->pageData;

$projectInfo = $pageData['projectInfo'];
$projectHeader = $pageData['projectHeader'];
/*
 * If exists projects list
 */
if (is_array($projectHeader)) {
?>
    <div id="MainHeader">
      <h1><?php echo $this->translate("#Project") ?> <?php print($projectHeader['projectTitle']) ?></h1>
    </div>

    <div class="Area">

      <div class="three columns alpha Right">
        <?php echo $this->translate("#Client:") ?>
      </div>
      <div class="six columns">
        <?php print($projectHeader['clientName']) ?>
      </div>
      <div class="three columns Right">
        <?php echo $this->translate("#Overhead:") ?>
      </div>
      <div class="two columns omega">
        <?php print($projectHeader['overhead']) ?> %
      </div>

      <div class="three columns alpha Right">
        <?php echo $this->translate("#Area activity:") ?>
      </div>
      <div class="six columns">
        <?php print($this->translate($projectHeader['areaActivity'])) ?>
      </div>
      <div class="three columns Right">
        <?php echo $this->translate("#Management fee:") ?>
      </div>
      <div class="two columns omega">
        <?php print($projectHeader['managementFee']) ?> % <!-- ### Talvez seja necessário esconder este campo (re: confusão da Beth sobre o seu uso) -->
      </div>

      <div class="three columns alpha Right">
        <?php echo $this->translate("#Our responsible:") ?>
      </div>
      <div class="six columns">
        <?php print($projectHeader['ourResponsible']) ?>
      </div>
      <div class="three columns Right">
        <?php echo $this->translate("#Contract value:") ?>
      </div>
      <div class="two columns omega">
        <?php print($projectHeader['contractValue']) ?>
      </div>

      <div class="three columns alpha Right">
        <?php echo $this->translate("#Responsible at client:") ?>
      </div>
      <div class="six columns">
        <?php print($projectHeader['responsibleAtClient']) ?>
      </div>
      <div class="three columns Right">
        <?php echo $this->translate("#Contract date:") ?>
      </div>
      <div class="two columns omega">
        <?php print($projectHeader['contractDate']) ?>
      </div>
    </div><!-- .Area -->

<?php
  if ($projectInfo['linkReceivables'] != "") {
?>

    <div id="tabs">
      <ul>
        <li><a href="#tabs-1">Recebimentos</a></li>
        <li><a href="#tabs-2">Pagamentos</a></li>
        <li><a href="#tabs-3">Equipe</a></li>
      </ul>

      <div id="tabs-1">
        <div class="Area">
           <h2>Recebimentos</h2>
           <table id="Produtos" class="display dataTable">
              <thead>
                <tr>
                  <th width="300">Produto</th>
                  <th width="50">Data prevista</th>
                  <th width="50">Data real</th>
                  <th width="50">Valor previsto</th>
                  <th width="50">Valor real</th>
                  <th width="1%">&nbsp;</th>
                </tr>
              </thead>
              <tbody>

                <!-- ### loop de carga das ações que são produto -->
                <tr>
                  <td>
                    <a href="<?php print($projectInfo['linkReceivable']) ?>"><?php print($projectInfo['receivableTitle']) ?></a>
                  </td>
                  <td>
                    <?php print($projectInfo['receivablePredictedDate']) ?>
                  </td>
                  <td>
                    <?php print($projectInfo['receivableRealDate']) ?>
                  </td>
                  <td class="Right">
                    <?php print($projectInfo['receivablePredictedValue']) ?>
                  </td>
                  <td class="Right">
                    <?php print($projectInfo['receivableRealValue']) ?>
                  </td>
                  <td>
                    <a href="#" class="anchorclass" rel="submenu1">Opções</a>
                    <div id="submenu1" class="anylinkcss">
                        <ul>
                          <li>
                            <!-- [# LINK PARA A EDIÇÃO DO PRODUTO ] -->
                            <a href="#">Editar</a>
                          </li>
                          <li>
                            <!-- [# LINK PARA FORM DE CONFIRMAÇÃO DE RECEBIMENTO -> VAI ABRIR EM BOX DE DIÁLOGO MODAL ] -->
                            <a href="<#">Informar recebimento</a>
                          </li>
                          <li>
                            <!-- [# LINK PARA PÁGINA DE DETALHAMENTO DO PRODUTO ] -->
                            <a href="">Detalhamento do produto</a>
                          </li>
                        </ul>
                    </div><!-- #submenu1 -->
                  </td>
                </tr>
                <!-- ### fim do loop de carga das ações que são produto -->

              </tbody>
            </table><br />
            <p>
              <!-- [# LINK PARA PÁGINA DE CRIAÇÃO DE RECEBIMENTO ] <?php print($projectInfo['linkReceivableCreate']) ?> -->
              <a href="#" class="button three columns alpha omega">Prever recebimento</a>
            </p>
          </div><!-- Area -->
        </div><!-- tabs-1 -->

        <div id="tabs-2">
          <div class="Area">
            <h2>Pagamentos</h2>

<!-- ### INSERÇÃO DO CÓDIGO DE PAYABLES.PHTML COM ALTERAÇÕES DE RPORTO -->

<?php
/*
 * If exists payables list
 */
    if (is_array($this->payablesList)) {
?>

<?php
/*
 * if there is payables in list
 */
      if (count($this->payablesList)) {
?>

<?php
/*
 * iterate list and print title
 */
        while (list(, $payableData) = each($this->payablesList)) {
?>
           <table id="Pagamentos" class="display dataTable">
              <thead>
                <tr>
                  <th width="300">Ação</th>
                  <th width="300">Beneficiado</th>
                  <th width="50">Data prevista</th>
                  <th width="50">Data real</th>
                  <th width="50">Valor previsto</th>
                  <th width="50">Valor real</th>
                  <th width="1%">&nbsp;</th>
                </tr>
              </thead>
              <tbody>

                <!-- ### loop de carga das ações que geram pagamentos -->
                <tr>
                  <td>
                    <a href="<?php print($projectInfo['linkOutlay']) ?>"><?php print($projectInfo['outlayActionTitle']) ?></a>
                  </td>
                  <td>
                    <a href="<?php print($projectInfo['linkSupplier']) ?>"><?php print($projectInfo['outlayActionSupplier']) ?></a>
                  </td>
                  <td>
                    <?php print($projectInfo['outlayPredictedDate']) ?>
                  </td>
                  <td>
                    <?php print($projectInfo['outlayRealDate']) ?>
                  </td>
                  <td class="Right">
                    <?php print($projectInfo['outlayPredictedValue']) ?>
                  </td>
                  <td class="Right">
                    <?php print($projectInfo['outlayRealValue']) ?>
                  </td>
                  <td>
                    <a href="#" class="anchorclass" rel="submenu1">Opções</a>
                    <div id="submenu1" class="anylinkcss">
                        <ul>
                          <li>
                            <!-- [# LINK PARA A EDIÇÃO DO PAGAMENTO ] -->
                            <a href="<?php print($projectInfo['outlayEditLink']) ?>">Editar</a>
                          </li>
                          <li>
                            <!-- [# LINK PARA FORM DE CONFIRMAÇÃO DE PAGAMENTO -> VAI ABRIR EM BOX DE DIÁLOGO MODAL ] -->
                            <a href="<?php print($projectInfo['outlayConfirmationLink']) ?>">Informar pagamento</a>
                          </li>
                          <li>
                            <!-- [# LINK PARA PÁGINA DE DETALHAMENTO DO PAGAMENTO ] -->
                            <a href="<?php print($projectInfo['linkOutlay']) ?>">Detalhamento do produto</a>
                          </li>
                        </ul>
                    </div><!-- #submenu1 -->
                  </td>
                </tr>
                <!-- ### fim do loop de carga das ações que são produto -->

              </tbody>
            </table><br />

            <p>
              <!-- [# LINK PARA PÁGINA DE CRIAÇÃO DE PAGAMENTO ]  -->
              <a href="#" class="button three columns alpha omega">Prever pagamento</a>
            </p>
<?php
        }  // loop iterate list and print titlei
?>

<?php
      } else { // end else there is payables in list
?>
            <p><?php print("Não há ações realizadas.") ?></p>

<?php
      } // end else there is payables in list
?>
<?php
    } else { // else exists payables list
?>
            <p><?php print("Não existe lista de ações realizadas.") ?></p>

<?php
    } // end exists payables list
?>

<!-- ### FIM DA INSERÇÃO DO CÓDIGO DE PAYABLES.PHTML -->

          </div><!-- Area -->
        </div><!-- tabs-2 -->

<!-- ### ACHO QUE O CONTEÚDO DESTA ABA É NOVO - NÃO ENCONTREI EM NENHUM PHTM -->
        <div id="tabs-3">
          <div class="Area">
            <h2>Equipe</h2>
            <table id="Equipe" class="display dataTable">
              <thead>
                <tr>
                  <th width="220">Nome</th>
                  <th width="80">Função</th>
                  <th width="100">E-mail</th>
                  <th width="100">Telefone</th>
                  <th width="100">&nbsp;</th>
                </tr>
              </thead>
              <tbody>
              <!-- ### loop de carga dos recursos humanos alocados ao projeto -->
                <tr>
                  <td>
                    <a href="<?php print($projectInfo['linkHumanResource']) ?>"><?php print($projectInfo['humanResourceName']) ?></a>
                  </td>
                  <td>
                    <?php print($projectInfo['humanResourceFunction']) ?>
                  </td>
                  <td>
                    <a href="mailto:<?php print($projectInfo['humanResourceEmail']) ?>"><?php print($projectInfo['humanResourceEmail']) ?></a>
                  </td>
                  <td>
                    <?php print($projectInfo['humanResourcePhone']) ?>
                  </td>
                  <td>
                    <a href="#" class="anchorclass" rel="submenu1">Opções</a>
                    <div id="submenu1" class="anylinkcss">
                        <ul>
                          <li>
                            <!-- [# LINK PARA A EDIÇÃO DO CONTATO ] -->
                            <a href="<?php print($projectInfo['humanResourceEditLink']) ?>">Editar</a>
                          </li>
                          <li>
                            <!-- [# LINK PARA PÁGINA DO CONTATO ] -->
                            <a href="<?php print($projectInfo['linkHumanResource']) ?>">Ver contato</a>
                          </li>
                        </ul>
                    </div><!-- #submenu1 -->
                  </td>
                </tr>
              <!-- ### loop de carga dos recursos humanos alocados ao projeto -->
              </tbody>
            </table><br />

            <p>
              <!-- [# LINK PARA PÁGINA DE VINCULAÇÃO DE CONTATO À EQUIPE DO PROJETO ] -->
              <a href="#" class="button three columns alpha omega">Incluir membro</a>
            </p>
          </div><!-- Area -->
        </div><!-- tabs-3 -->
      </div><!-- #tabs -->
<?php
  }
?>
<?php
  if ($projectInfo['linkPayables'] != "") {
?>
      <p>
        <a class="info" href="<?php print($projectInfo['linkPayables']) ?>">Consultar ações realizadas</a><br />
      </p>
<?php
  }
?>
<?php
  if ($projectInfo['linkUnacknowledged'] != "") {
?>
      <p>
        <a class="info" href="<?php print($projectInfo['linkUnacknowledged']) ?>">Ações com início a confirmar</a><br />
      </p>
<?php
  }
?>
<?php
  if ($projectInfo['linkTree'] != "") {
?>
      <p>
        <a class="info" href="<?php print($projectInfo['linkTree']) ?>">Árvore de ações</a><br />
      </p>
<?php
  }
?>

  <h2>Produtos do Projeto</h2>
<?php
/*
 * iterate list and print title
 */

    $actionsList = $projectInfo['actionsList'];

    while (list(, $actionInfo) = each($actionsList)) {
?>
<p class="project_product_line">
<?php print($actionInfo['title']) ?>&nbsp;<?php print($actionInfo['specialAction']) ?> |
(<?php print($actionInfo['brood']) ?>) |
<?php if (isset($actionInfo['editLink'])) { ?>
<a href="<?php print($actionInfo['editLink']) ?>">Editar</a>
<?php } ?>
</p>


<?php
}  // loop iterate list and print titlei
?>



<p />
<br /><br /><a href="<?php print($projectInfo['linkActionCreate']) ?>">Criar Nova Ação</a>


<?php
} else { // else exists projects list
?>
    <?php print("Não há informações para este projeto.") ?>

    <?php
} // end exists projects list
?>
