<?php

$pageData = $this->pageData;


        //  projectHeader
        //    id
        //    projectTitle
        //    clientName
        //    areaActivity
        //    ourResponsible
        //    responsibleAtClient
        //    overhead
        //    managementFee
        //    contractValue
        //    contractDate
        //
$projectHeader = $pageData['projectHeader'];

        // receivablesList
        //   * id =>
        //      productTitle
        //      predictedDate
        //      realDate
        //      predictedValue
        //      realValue

$receivablesList = $pageData['receivablesList'];

$actionsList = $pageData['actionsTree'];
$outlaysList = $pageData['outlaysList'];
$staffList = $pageData['staffList'];

?>
    <div id="MainHeader">
      <h1><?php echo $this->translate("#Project") ?> <?php print($projectHeader['projectTitle']) ?></h1>
    </div>

    <div class="Area">

      <div class="three columns alpha Right">
        <?php echo $this->translate("#Client:") ?>
      </div>
      <div class="six columns">
        <?php print($projectHeader['clientName']) ?>
      </div>
      <div class="three columns Right">
        <?php echo $this->translate("#Overhead:") ?>
      </div>
      <div class="two columns omega">
        <?php print($projectHeader['overhead']) ?> %
      </div>

      <div class="three columns alpha Right">
        <?php echo $this->translate("#Area activity:") ?>
      </div>
      <div class="six columns">
        <?php print($this->translate($projectHeader['areaActivity'])) ?>
      </div>
      <div class="three columns Right">
        <?php echo $this->translate("#Management fee:") ?>
      </div>
      <div class="two columns omega">
        <?php print($projectHeader['managementFee']) ?> % <!-- ### Talvez seja necessário esconder este campo (re: confusão da Beth sobre o seu uso) -->
      </div>

      <div class="three columns alpha Right">
        <?php echo $this->translate("#Our responsible:") ?>
      </div>
      <div class="six columns">
        <?php print($projectHeader['ourResponsible']) ?>
      </div>
      <div class="three columns Right">
        <?php echo $this->translate("#Contract value:") ?>
      </div>
      <div class="two columns omega">
        <?php print($projectHeader['contractValue']) ?>
      </div>

      <div class="three columns alpha Right">
        <?php echo $this->translate("#Responsible at client:") ?>
      </div>
      <div class="six columns">
        <?php print($projectHeader['responsibleAtClient']) ?>
      </div>
      <div class="three columns Right">
        <?php echo $this->translate("#Contract date:") ?>
      </div>
      <div class="two columns omega">
        <?php print($projectHeader['contractDate']) ?>
      </div>
    </div><!-- .Area -->

    <div id="tabs">
      <ul>
        <li><a href="#tabs-1"><?php echo $this->translate("#Receiving") ?></a></li>
        <li><a href="#tabs-2"><?php echo $this->translate("#Payments") ?></a></li>
        <li><a href="#tabs-3"><?php echo $this->translate("#Staff") ?></a></li>
        <li><a href="#tabs-4"><?php echo $this->translate("#Actions") ?></a></li>
      </ul>

      <div id="tabs-1">
        <div class="Area">
           <h2><?php echo $this->translate("#Receiving") ?></h2>
           <table id="Produtos" class="display dataTable">
              <thead>
                <tr>
                  <th width="300"><?php echo $this->translate("#Product") ?></th>
                  <th width="50"><?php echo $this->translate("#Predicted date") ?></th>
                  <th width="50"><?php echo $this->translate("#Real date") ?></th>
                  <th width="50"><?php echo $this->translate("#Predicted value") ?></th>
                  <th width="50"><?php echo $this->translate("#Real value") ?></th>
                  <th width="1%">&nbsp;</th>
                </tr>
              </thead>
              <tbody>

                <!-- ### loop de carga das ações que são produto -->
<?php
foreach($receivablesList as $id => $productInfo) {
?>
                <tr>
                  <td>
                    <a href="/projects/receivable/detail/?id=<?php print($id) ?>"><?php print($productInfo['productTitle']) ?></a>
                  </td>
                  <td>
                    <?php print($productInfo['predictedDate']) ?>
                  </td>
                  <td>
                    <?php print($productInfo['realDate']) ?>
                  </td>
                  <td class="Right">
                    <?php print($productInfo['predictedValue']) ?>
                  </td>
                  <td class="Right">
                    <?php print($productInfo['realValue']) ?>
                  </td>
                  <td>
                    <a href="#" class="anchorclass" rel="submenu1"><?php echo $this->translate("#Options") ?></a>
                    <div id="submenu1" class="anylinkcss">
                        <ul>
                          <li>
                            <!-- [# LINK PARA A EDIÇÃO DO PRODUTO ] -->
                            <a href="/projects/action/edit/?id=<?php echo $id ?>"><?php echo $this->translate("#Edit") ?></a>
                          </li>
                          <li>
                            <!-- [# LINK PARA FORM DE CONFIRMAÇÃO DE RECEBIMENTO -> VAI ABRIR EM BOX DE DIÁLOGO MODAL ] -->
                            <a href="/projects/receivable/notify/?id=<?php echo '/#' ?>"><?php echo $this->translate("#Notify receiving") ?></a>
                          </li>
                          <li>
                            <!-- [# LINK PARA PÁGINA DE DETALHAMENTO DO PRODUTO ] -->
                            <a href="/projects/action/detail/?id=<?php echo $id ?>"><?php echo $this->translate("#Product details") ?></a>
                          </li>
                        </ul>
                    </div><!-- #submenu1 -->
                  </td>
                </tr>
<?php
}
?>

              </tbody>
            </table><br />
              <a href="/projects/receivable/create/?project=<?php echo $projectHeader['id'] ?>" class="button three columns alpha omega"><?php echo $this->translate("#Predict receiving") ?></a>
        <a href="/projects/project/payables/?id=<?php print($projectHeader['id']) ?>" class="button three columns alpha omega">Consultar ações realizadas</a>
        <a href="/projects/project/unacknowledged/?id=<?php print($projectHeader['id']) ?>" class="button three columns alpha omega">Ações com início a confirmar</a>
<a href="/projects/action/create/?project=<?php print($projectHeader['id']) ?>" class="button three columns alpha omega">Criar Nova Ação</a>


          </div><!-- Area -->
        </div><!-- tabs-1 -->

        <div id="tabs-2">
          <div class="Area">
            <h2><?php echo $this->translate("#Payments") ?></h2>

<!-- ### INSERÇÃO DO CÓDIGO DE PAYABLES.PHTML COM ALTERAÇÕES DE RPORTO -->

<?php
/*
 * if there is payables in list
 */
      if (count($outlaysList)) {
?>


           <table id="Pagamentos" class="display dataTable">
              <thead>
                <tr>
                  <th width="300"><?php echo $this->translate("#Action") ?></th>
                  <th width="300"><?php echo $this->translate("#Payee") ?></th>
                  <th width="50"><?php echo $this->translate("#Predicted date") ?></th>
                  <th width="50"><?php echo $this->translate("#Real date") ?></th>
                  <th width="50"><?php echo $this->translate("#Predicted value") ?></th>
                  <th width="50"><?php echo $this->translate("#Real value") ?></th>
                  <th width="1%">&nbsp;</th>
                </tr>
              </thead>
              <tbody>

<?php

foreach($outlaysList as $id => $outlayInfo) {
?>
                <!-- ### loop de carga das ações que geram pagamentos -->
                <tr>
                  <td>
                    <a href="/projects/action/detail/?id=<?php print($outlayInfo['actionId']) ?>"><?php print($outlayInfo['actionTitle']) ?></a>
                  </td>
                  <td>
                    <a href="<?php print(($outlayInfo['payeeId'] > 0 ? '/register/contact/detail/?id=' . $outlayInfo['payeeId'] : "#")) ?>"><?php print($outlayInfo['payeeName']) ?></a>
                  </td>
                  <td>
                    <?php print($outlayInfo['predictedDate']) ?>
                  </td>
                  <td>
                    <?php print($outlayInfo['realDate']) ?>
                  </td>
                  <td class="Right">
                    <?php print($outlayInfo['predictedValue']) ?>
                  </td>
                  <td class="Right">
                    <?php print($outlayInfo['realValue']) ?>
                  </td>
                  <td>
                    <a href="#" class="anchorclass" rel="submenu1"><?php echo $this->translate("#Options") ?></a>
                    <div id="submenu1" class="anylinkcss">
                        <ul>
                          <li>
                            <!-- [# LINK PARA A EDIÇÃO DO PAGAMENTO ] -->
                            <a href="/projects/outlay/edit/?id=<?php print($id) ?>"><?php echo $this->translate("#Edit") ?></a>
                          </li>
                          <li>
                            <!-- [# LINK PARA FORM DE CONFIRMAÇÃO DE PAGAMENTO -> VAI ABRIR EM BOX DE DIÁLOGO MODAL ] -->
                            <a href="/projects/outlay/confirm/?id=<?php print($id) ?>"><?php echo $this->translate("#Confirm payment") ?></a>
                          </li>
                          <li>
                            <!-- [# LINK PARA PÁGINA DE DETALHAMENTO DO PAGAMENTO ] -->
                            <a href="/projects/outlay/detail/?id=<?php print($id) ?>"><?php echo $this->translate("#Outlay details") ?></a>
                          </li>
                        </ul>
                    </div><!-- #submenu1 -->
                  </td>
                </tr>
<?php
}
?>
                <!-- ### fim do loop de carga das ações que são produto -->

              </tbody>
            </table><br />

            <p>
              <!-- [# LINK PARA PÁGINA DE CRIAÇÃO DE PAGAMENTO ]  -->
              <a href="#" class="button three columns alpha omega"><?php echo $this->translate("#Predict outlay") ?></a>
            </p>

<?php
      } else { // end else there is payables in list
?>
            <p><?php print($this->translate("#There is no outlays related to this project.")) ?></p>

<?php
      } // end else there is payables in list
?>

<!-- ### FIM DA INSERÇÃO DO CÓDIGO DE PAYABLES.PHTML -->

          </div><!-- Area -->
        </div><!-- tabs-2 -->

<!-- ### ACHO QUE O CONTEÚDO DESTA ABA É NOVO - NÃO ENCONTREI EM NENHUM PHTM -->
        <div id="tabs-3">
          <div class="Area">
            <h2>Equipe</h2>
            <table id="Equipe" class="display dataTable">
              <thead>
                <tr>
                  <th width="220"><?php echo $this->translate("#Name") ?></th>
                  <th width="80"><?php echo $this->translate("#Function") ?></th>
                  <th width="100"><?php echo $this->translate("#Email") ?></th>
                  <th width="100"><?php echo $this->translate("#Phone number") ?></th>
                  <th width="100">&nbsp;</th>
                </tr>
              </thead>
              <tbody>
              <!-- ### loop de carga dos recursos humanos alocados ao projeto -->
<?php

foreach($staffList as $id => $staffInfo) {
?>
                <tr>
                  <td>
                    <a href="/register/contact/detail/?id=<?php print($staffInfo['contactId']) ?>"><?php print($staffInfo['staffName']) ?></a>
                  </td>
                  <td>
                    <a href="/projects/human-resource/edit/?id=<?php print($id) ?>"><?php print($staffInfo['positionDescription']) ?></a>
                  </td>
                  <td>
                    <a href="mailto:<?php print($staffInfo['staffEmail']) ?>"><?php print($staffInfo['staffEmail']) ?></a>
                  </td>
                  <td>
                    <?php print($staffInfo['staffPhoneNumber']) ?>
                  </td>
                  <td>
                    <a href="#" class="anchorclass" rel="submenu1"><?php echo $this->translate("#Options") ?></a>
                    <div id="submenu1" class="anylinkcss">
                        <ul>
                          <li>
                            <!-- [# LINK PARA A EDIÇÃO DO CONTATO ] -->
                            <a href="/projects/human-resource/edit/?=<?php print($id) ?>"><?php echo $this->translate("#Edit") ?></a>
                          </li>
                          <li>
                            <!-- [# LINK PARA PÁGINA DO CONTATO ] -->
                            <a href="/register/contact/detail/?id=<?php print($staffInfo['contactId']) ?>"><?php echo $this->translate("#Contact details") ?></a>
                          </li>
                        </ul>
                    </div><!-- #submenu1 -->
                  </td>
                </tr>
<?php
}
?>
              <!-- ### loop de carga dos recursos humanos alocados ao projeto -->
              </tbody>
            </table><br />

            <p>
              <!-- [# LINK PARA PÁGINA DE VINCULAÇÃO DE CONTATO À EQUIPE DO PROJETO ] -->
              <a href="" class="button three columns alpha omega"><?php echo $this->translate("#Add staff member") ?></a>
            </p>
          </div><!-- Area -->
        </div><!-- tabs-3 -->





        <div id="tabs-4">
          <div class="Area">
            <h2><?php echo $this->translate("#Actions") ?></h2>
    <table id="tree" border="1">
    	<thead>
    		<tr>
    			<th width="200" align="left"><?php echo $this->translate("#Action") ?></th>
    			<th width="200" align="left"><?php echo $this->translate("#Responsible") ?></th>
    			<th width="100" align="left"><?php echo $this->translate("#Pred. begin date") ?></th>
    			<th width="100" align="left"><?php echo $this->translate("#Real begin date") ?></th>
    			<th width="100" align="left"><?php echo $this->translate("#Pred. finish date") ?></th>
    			<th width="100" align="left"><?php echo $this->translate("#Real finish date") ?></th>
    		</tr>
    	</thead>
    	<tbody>


<?php


foreach ($actionsList as $id => $actionData) {
    $nodeId = "node-" . $id;
    $childOf = $actionData['subordinatedTo'];
    if ($childOf > 0) {
        $classId = "\"child-of-node-$childOf\"";
        $classId = 'class = ' . $classId;
    }

?>


        <tr id="<?php print ($nodeId) ?>" <?php print (($childOf > 0 ? $classId : '')) ?>>
          <td><a href='/projects/action/detail/?id=<?php print($id) ?>'><?php print ($actionData['title']) ?></a></td>
          <td><?php print ($actionData['responsibleName']) ?></td>
          <td><?php print ($actionData['predictedBeginDate']) ?></td>
          <td><?php print ($actionData['realBeginDate']) ?></td>
          <td><?php print ($actionData['predictedFinishDate']) ?></td>
          <td><?php print ($actionData['realFinishDate']) ?></td>
        </tr>
<?php
}

?>
        <!-- # Fim do loop -->
      </tbody>
    </table>
<br />
          </div><!-- Area -->
        </div><!-- tabs-4 -->
      </div><!-- #tabs -->

