<?php
  $pageData = $this->pageData;
  $personData = $pageData['personData'];
?>

        <div id="MainHeader">
          <h1><?php print($this->translate("#Project")); ?> <a href="/projects/project/detail/?id=<?php print($personData['projectId']) ?>"><?php print($personData['projectTitle']) ?></a></h1>
        </div><!-- MainHeader -->
        <div class="TituloForm">
          <h2><?php print(sprintf($this->translate("#%s's participation in the project"), $personData['name'])); ?></h2>

        </div>
        <div class="Area">

          <div class="two columns alpha Right">
            <?php print($this->translate("#Predicted:")); ?>
          </div>
          <div class="two columns">
            <?php print($personData['totalValue']); ?>
          </div>
          <div class="two columns alpha Right">
            <?php print($this->translate("#Contracted:")); ?>
          </div>
          <div class="two columns">
            <?php print($personData['contractedValue']); ?>
          </div>
          <div class="two columns alpha Right">
            <?php print($this->translate("#Payed:")); ?>
          </div>
          <div class="two columns">
            <?php print($personData['payedValue']); ?>
          </div>
        </div>



        <div id="tabs">
          <ul>
            <li><a href="#tabs-actions"><?php echo $this->translate("#Actions") ?></a></li>
          </ul>

          <div id="tabs-actions">
            <table id="SubActions" class="display dataTable">
              <thead>
                <tr>
                  <th width="200"><?php print($this->translate("#Action")); ?></th>
                  <th width="75"><?php print($this->translate("#Action Status")); ?></th>
                  <th width="75"><?php print($this->translate("#Value")); ?></th>
                  <th width="80"><?php print($this->translate("#Status")); ?></th>
                  <th width="10">&nbsp;</th>
                </tr>
              </thead>
              <tbody>
<?php
  $personActions = $personData['personActions'];
  foreach ($personActions as $id => $actionData) {
?>
                <!-- ### loop de carga das ações subordinadas a esta ação -->
                <tr>
                  <td><a href="/projects/action/detail/?id=<?php print($id);?>"><?php print($actionData['title']) ?></a></td>
                  <td><?php print($actionData['actionStatus']); ?></td>
                  <td><?php print($actionData['totalValue']); ?></td>
                  <td><?php print($this->translate($actionData['teamMemberStatus'])); ?></td>
                      <td>
                    <a href="#" class="button one column alpha omega anchorclass" rel="submenu1"><?php print($this->translate("#Options")); ?></a>
                    <div id="submenu1" class="anylinkcss">
                        <ul>
<?php

if ($actionData['canProvideOutlay']) {
?>


                          <li>
                            <a href="/finances/outlay/create/?teamMember=<?php echo $actionData['teamMemberId'] ?>"><?php echo $this->translate("#Provide outlay") ?></a>
                          </li>

<?php
}
?>
<?php

if ($actionData['canNotifyOutlay']) {
?>


                          <li>
                            <a href="/finances/outlay/notify/?id=<?php echo $actionData['outlayId'] ?>"><?php echo $this->translate("#Notify outlay") ?></a>
                          </li>

<?php
}
?>
    <?php
    if ($actionData['canContractFlag']) {
?>
                        <li>
                          <a class="parent_info" href="/resources/team-member/contract/?id=<?php print($actionData['teamMemberId']);?>" ><?php print($this->translate("#Confirm team member contracting")); ?></a>
                        </li>

<?php
    }
?>

<?php
    if($actionData['canEditResource']) {

?>
                        <li>
                          <a href="/resources/team-member/edit/?id=<?php print($actionData['teamMemberId']) ?>"><?php print($this->translate("#Edit")); ?></a>
                        </li>

<?php
    }
?>

<?php

if ($actionData['canRemoveTeamMember']) {
?>


                          <li>
                            <a href="/resources/team-member/remove/?id=<?php echo $actionData['teamMemberId'] ?>"><?php echo $this->translate("#Remove") ?></a>
                          </li>

<?php
}
?>

                        </ul>
                    </div><!-- #submenu1 -->
                  </td>
                </tr>
              <!-- ### fim do loop de carga das ações subordinadas a esta ação -->
<?php
  }
?>
              </tbody>
            </table>
          </div><!-- #tabs-actions -->


        </div><!-- #tabs -->
        <!-- ### Será preciso montar a tabela de recursos materias, idêntica à de recursos humanos, assim que forem tratados pelo sistema -->
