<h2>Recebimentos</h2>
<?php 
/*
 * If exists projects list
 */
if (is_array($this->projectInfo)) {
    $projectData = $this->projectInfo;
?>
Projeto: <a href="<?php print($projectData['linkDetail']) ?>"><?php print($projectData['title']) ?></a><br />
<p />
<?php print($projectData['projectValue']) ?><br />
<p />
<hr>
<?php 
/*
 * iterate list and print title
 */

    $receivingsList = $projectData['receivingsList'];
    
    while (list(, $receivingInfo) = each($receivingsList)) {
?>

<?php print($receivingInfo['title']) ?> | <?php print($receivingInfo['predictedDate']) ?> | <?php print($receivingInfo['predictedValue']) ?>

<?php if (isset($receivingInfo['linkEdit'])) { ?>
<a href="<?php print($receivingInfo['linkEdit']) ?>">Editar</a>
<?php } ?>

<br />


    
<?php
}  // loop iterate list and print titlei
?>



    
<?php
} else { // else exists projects list 
?>
    <?php print("Não há informações para este projeto.") ?>

    <?php
} // end exists projects list
?>
