<?php 
/*
 * If exists projects list
 */
if (is_array($this->projectInfo)) {
    $projectData = $this->projectInfo;
?>
<p class="project_title">Projeto: <a href="<?php print($projectData['linkDetail']) ?>"><?php print($projectData['title']) ?></a></p>
<p />
<p class="info"><?php print($projectData['projectValue']) ?><br /></p>
<p />
<hr>
<h2>Recebimentos</h2>
<?php 
/*
 * iterate list and print title
 */

    $receivablesList = $projectData['receivablesList'];
    
    while (list(, $receivableInfo) = each($receivablesList)) {
?>

<p class="receivable_line"><?php print($receivableInfo['title']) ?> | <?php print($receivableInfo['predictedDate']) ?> | <?php print($receivableInfo['predictedValue']) ?>

<?php if (isset($receivableInfo['editLink'])) { ?>
<a href="<?php print($receivableInfo['editLink']) ?>">Editar</a>
<?php } ?>

<?php 
    $productsList = $receivableInfo['productsList'];
    while (list(, $productInfo) = each($productsList)) {
?>

<p class='product_info'>
    * <a class='product_info' href="<?php print($productInfo['linkDetail']) ?>"><?php print($productInfo['title']) ?></a>
</p>


<?php
}  // loop iterate list and print titlei
?>





</p>





    
<?php
}  // loop iterate list and print titlei
?>



    
<?php
} else { // else exists projects list 
?>
    <?php print("Não há informações para este projeto.") ?>

    <?php
} // end exists projects list
?>
