  		<div id="Header" class="fifteen columns">
  			<h1>
      		<img src="/images/logoC3OP.png" alt="C3OP" title="C3OP" height="61" width="227">
        </h1>
        <p>
          Olá, você não está logado.
        </p>
  		</div><!-- #Header -->
  		<div id="Logo" class="one column">
  			<img src="/images/logosmlIets.png" alt="Iets" title="Iets" height="61" width="53">
     	</div><!-- #Logo -->

  		<div id="Menu" class="sixteen columns">
  		</div><!-- #Menu -->
      
      
      <div class="spacer four columns alpha"></div>
      <div id="Main" class="eight columns">
        <div class="spacer one column alpha"></div>
        <div id="MainHeader" class="six columns">
            <h1>Login</h1>
    		</div><!-- #MainHeader -->  		
    		<div class="spacer one column omega"></div>
    		<br class="clear">

    		<div class="spacer one column alpha"></div>
        <div id="Stage" class="six columns">
<!-- content -->
<?php echo $this->layout()->content ?>
<!-- /content -->
        </div><!-- Stage -->
      	<div class="spacer one column omega"></div>
        
      </div><!-- #Main -->
    	<div class="spacer four columns omega"></div>

