<?php
  $pageData = $this->pageData;
?>
      <div id="Header" class="fifteen columns">
<?php
  if ($pageData['loggedIn']) {
?>
        <!-- loggedIn -->
        <p>
          <?php print($this->translate("#Hi")) ?>&nbsp;<a href="/auth/user/edit/?id=<?php echo $pageData['id']?>"><?php echo $pageData['userName']?></a> |
          <a href="/auth/logout"><?php print($this->translate("#Logout")) ?></a>
        </p>
      </div><!-- #Header -->
      <div id="Logo" class="one column">
        <img src="/images/logosmlIets.png" alt="Iets" title="Iets" height="61" width="53">
      </div><!-- #Logo -->
      <div id="Menu" class="sixteen columns">
        <ul>
<?php
    foreach ($pageData['navigationTabs'] as $tab => $tabData) {
      if ($tabData['active']) {
        $activeClass = ' class="active"';
      } else {
        $activeClass = '';
      }
?>
          <li <?php print($activeClass) ?>><a href="<?php print($tabData['url']) ?>"><?php print($tabData['label']) ?></a></li>
<?php
    }
?>

        </ul>
          <br clear="all">
          <?php /*print_r( $pageData['breadcrumb'])*/ ?>
      </div><!-- #Menu -->
	  
	  <div id="Breadcrumb" class="sixteen columns">
		  <a href="" class="financas">Home Financas</a>
		  <a href="" class="financas">Todos os projetos</a>
		  <a href="" class="projetos">Home projetos</a>
		  <a href="" class="projetos">Projeto 1 Infancia</a>
		  <a href="" class="projetos">Sintese das mesas</a>
		  <a href="" class="noback projetos">Elaborar relatoria da mesa 1</a>
	  </div><!-- #Breadcrumb -->
	  
      <!-- /loggedIn -->
<?php
  } else {
?>
      <!-- nao loggedIn -->
      <p>
        <?php print($this->translate("#Please login.")) ?>
      </p>
    </div><!-- #Header -->
    <div id="Logo" class="one column">
      <img src="/images/logosmlIets.png" alt="Iets" title="Iets" height="61" width="53">
    </div><!-- #Logo -->
    <div id="Menu" class="sixteen columns">
    </div><!-- #Menu -->
    <!-- /nao loggedIn -->
<?php
  }
?>
