<?php
  $pageData = $this->pageData;

  $projectId = $pageData['projectId'];
  $contactId = $pageData['contactId'];
  $responsibleLabel = $pageData['responsibleLabel'];


  if ($pageData['responsibleType'] == C3op_Resources_ResponsibleTypeConstants::TYPE_TEAM_MEMBER) {
      $responsibleLink = "<a href='/projects/project/engagement/?id=$projectId&contact=$contactId'>$responsibleLabel</a>";
  } else {
      $responsibleLink = "<a href='/register/institution/detail/?id=$contactId'>$responsibleLabel</a>";

  }

?>
<?php print($this->translate("#Responsible was predicted")); ?>
<br class="clear" />
<?php
if ($contactId) {
?>
<?php print(sprintf($this->translate("#%s was assigned responsible for this action"), $responsibleLink)); ?>
<?php
}
?>
