<?php
$headerData = $this->headerData;
?>
<div id="MainHeader">
    <h1><span class="weight_normal"><?php print($this->translate('#Confirm contracting')); ?></span> <?php print($headerData["responsibleName"]) ?></h1>
    <div class="TituloForm">
        <h2><?php print($this->translate("#In action ")); ?> <a href="/projects/action/detail/?id=<?php print($headerData["actionId"]) ?>"><?php print($headerData["actionTitle"]) ?></a></h2>
    </div>
    <p><?php print($this->translate('#Enter below the contracted dates for the beginning and end of the action')); ?></p>
</div>

<form id="form" action="<?php echo $this->escape($this->form->getAction()); ?>" method="<?php echo $this->escape($this->form->getMethod()); ?>">
<table>
  <?php echo $this->form->id ?>
  <?php echo $this->form->predictedBeginDate ?>
  <?php echo $this->form->predictedFinishDate ?>
  <div class="offset-by-three alpha ">  <?php echo $headerData["providedBudget"] ?></div>
  <?php echo $this->form->value ?>
  <?php echo $this->form->observation ?>
  <?php echo $this->form->submit ?>
</table>
</form>
