<?php
  $pageData = $this->pageData;
?>
    <!-- Initializing jquery.meio.mask -->
    <script type="text/javascript" charset="utf-8">
      $(document).ready(function() {
        $.mask.masks = $.extend($.mask.masks, {
        });
        $('input:text').setMask();
      });

    $(document).ready(function(){

        $('#linkage-label').hide();
        $('#linkage').hide();
        $('#institution-label').hide();
        $('#institution').hide();
        if ($("#value").length > 0){
            $('#value-label').hide();
            $('#value').hide();
        }
        $('#submit').hide();

        $('#responsibleType-service').click(function(){
            populateResponsibleAtSupplier();
            $('#linkage-label').show();
            $('#linkage').show();
            $('#linkage').prop('disabled', true);
            $('#institution-label').show();
            $('#institution').show();
            if ($("#value").length > 0){
                $('#value-label').show();
                $('#value').show();
            }
            $('#submit').show();
            })

        $('#responsibleType-teamMember').click(function(){
            initLinkages();
            $('#linkage').prop('disabled', false);
            $('#linkage-label').show();
            $('#linkage').show();
            $('#institution-label').hide();
            $('#institution').hide();
            if ($("#value").length > 0){
                $('#value-label').show();
                $('#value').show();
            }
            $('#submit').show();
            })

    });


    </script>

          <script type="text/javascript">
            function populateResponsibleAtSupplier() {
              var id = $('#institution').val();

              if (id > 0) {
                $.getJSON('/resources/responsible/populate-contacts-field/?id=' + id, function(data) {
                    var html = '';
                    var len = data.length;
                    html += '<option value="0">(<?php print($this->translate("#choose someone")); ?>)</option>';
                    for (var i = 0; i< len; i++) {
                    html += '<option value="' + data[i].id + '">' + data[i].name + '</option>';
                    }
                    $('#linkage').prop('disabled', false);
                    $('#linkage').empty();
                    $('#linkage').append(html);
                });
              } else {
                    $('#linkage').prop('disabled', true);
                    $('#linkage').empty();

              }


            }

            function initLinkages() {
                $.getJSON('/resources/responsible/populate-contacts-field/?id=0', function(data) {
                    var html = '';
                    var len = data.length;
                    html += '<option value="0">(<?php print($this->translate("#choose someone")); ?>)</option>';
                    for (var i = 0; i< len; i++) {
                    html += '<option value="' + data[i].id + '">' + data[i].name + '</option>';
                    }
                    $('#linkage').prop('disabled', false);
                    $('#linkage').empty();
                    $('#linkage').append(html);
                });


            }


          </script>




<script>
function submitResponsibleForm()
{


$.post("/resources/responsible/create", $("#newResponsibleForm").serialize(), function(successReturn){
      $('#responsibleDiv').html(successReturn);
    });
}
</script>
<form id="newResponsibleForm" action="<?php echo $this->escape($this->form->getAction()); ?>" method="<?php echo $this->escape($this->form->getMethod()); ?>">
<table>
  <?php echo $this->form->project ?>
  <?php echo $this->form->action ?>
  <?php echo $this->form->responsibleType ?>
  <?php echo $this->form->institution ?>
  <br class="clear" />
  <?php echo $this->form->linkage ?>
  <?php
  if ($this->pageData['canSeeFinances']) {
    echo $this->form->value;

  }

  ?>
  <?php echo $this->form->submit ?>
</table>
</form>
