<?php
$headerData = $this->headerData;
?>
<div id="MainHeader">
<h1><?php print($this->translate('#Confirm dismissing')); ?> <?php print($headerData["responsibleName"]) ?></h1>
<div class="TituloForm">
    <h2><?php print($this->translate("#In action ")); ?> <?php print($headerData["actionTitle"]) ?></h2>
</div><p><?php print($this->translate('#Enter below the reason for dismissing')); ?></p>
</div>

<?php echo $this->form; ?>
