<?php
  $pageData = $this->pageData;
?>
    <!-- Initializing jquery.meio.mask -->
    <script type="text/javascript" charset="utf-8">
      $(document).ready(function() {
        $.mask.masks = $.extend($.mask.masks, {
        });
        $('input:text').setMask();
      });

      $(document).ready(function() {
            var type = $('input[name=responsibleType]:checked').val();

            if (type == 'teamMember') {
                $('#institution-label').hide();
                $('#institution').hide();
            }

      });

    </script>

          <script type="text/javascript">
            function typeHasChanged() {
                var type = $('input[name=responsibleType]:checked').val();

                var linkage = $('#linkage').val();

                if (type == 'teamMember') {

                    $.getJSON('/resources/responsible/populate-contacts-field/?id=0', function(data) {
                        var html = '';
                        var len = data.length;
                        html += '<option value="0">(escolha uma pessoa)</option>';
                        for (var i = 0; i< len; i++) {
                        html += '<option value="' + data[i].id + '">' + data[i].name + '</option>';
                        }
                        $('#institution-label').hide();
                        $('#institution').hide();
                        $('#linkage').empty();
                        $('#linkage').append(html);
                        $('#linkage').val(linkage);

                    });



                } else {
                    typeHasChangedToService();
                }
            }

            function typeHasChangedToService() {
                populateInstitutionsField();
                $('#linkage').hide();
                $('#linkage').prop('disabled', true);
//                var linkage = $('#linkage').val();
//                populateResponsibleAtSupplier();
//                $('#linkage').val(linkage);

            }

            function populateInstitutionsField() {
                var institution = $('#institution').val();

                $.getJSON('/resources/responsible/populate-institutions-field', function(data) {
                    var html = '';
                    var len = data.length;
                    html += '<option value="0">(escolha uma pessoa)</option>';
                    for (var i = 0; i< len; i++) {
                    html += '<option value="' + data[i].id + '">' + data[i].name + '</option>';
                    }
                    $('#institution').empty();
                    $('#institution').append(html);
                    $('#institution').val(institution);

                });
                $('#institution-label').show();
                $('#institution').show();


            }

            function populateResponsibleAtSupplier() {
              var id = $('#institution').val();

              if (id > 0) {
                $.getJSON('/resources/responsible/populate-contacts-field/?id=' + id, function(data) {
                    var html = '';
                    var len = data.length;
                    html += '<option value="0">(escolha uma pessoa)</option>';
                    for (var i = 0; i< len; i++) {
                    html += '<option value="' + data[i].id + '">' + data[i].name + '</option>';
                    }
                    $('#linkage').empty();
                    $('#linkage').append(html);
                });
              } else {
                    $('#linkage').prop('disabled', true);
                    $('#linkage').empty();
              }
            }
          </script>




<script>
function submitResponsibleForm()
{


$.post("/resources/responsible/create", $("#newResponsibleForm").serialize(), function(successReturn){
      $('#responsibleDiv').html(successReturn);
    });
}
</script>
<form id="newResponsibleForm" action="<?php echo $this->escape($this->form->getAction()); ?>" method="<?php echo $this->escape($this->form->getMethod()); ?>">
<table>
  <?php echo $this->form->id ?>
  <?php echo $this->form->project ?>
  <?php echo $this->form->action ?>
  <?php echo $this->form->responsibleType ?>
  <?php echo $this->form->institution ?>
  <br class="clear" />
  <?php echo $this->form->linkage ?>
  <?php
  if ($this->pageData['canSeeFinances']) {
    echo $this->form->value;

  }

  ?>
  <?php echo $this->form->submit ?>
</table>
</form>
