          <div class="two columns alpha">
            <span class="label">Responsavel:</span>
          </div>
          <div class="twelve columns">
              <a anchor="responsible"></a>

            <a id="responsibleButton" class="button" href="#responsible">Definir responsável</a>
          <!--<div id="responsibleDiv" class="slidingDiv" style="background:#fff;padding:5px;">-->
		  <div id="responsibleDiv">
              <h3>Definir responsável</h3>
              <div id="responsibleFormDiv">&nbsp;</div>
				<br class="clear"/>
                <!--<a class="alpha" href="#responsible" id="hideResponsibleHref">Esconder</a>-->
				<a class="button" href="javascript:closeResponsibleDiv();" id="hideResponsibleHref">Esconder</a>
              </div>
          </div>

