          <div class="two columns alpha">
            <span class="label">Responsavel:</span>
          </div>
          <div class="twelve columns">
              <a anchor="responsible"></a>
<a href='#' class ='anchorclass' rel ='submenuResponsible'>Manuel Thedim</a> é responsável por essa ação. (Realizada)
                  <div id="submenuResponsible" class="anylinkcss">
                      <ul>
                          <li>
                              <a href="/projects/project/engagement/?id=15&contact=28">Participação no projeto</a>
                          </li>

                          <li>
                              <a href="javascript:callResponsibleEdit(9)">Editar responsável</a>
                          </li>
                      </ul>
                  </div>

          <!--<div id="responsibleDiv" class="slidingDiv" style="background:#fff;padding:5px;">-->
		  <div id="responsibleDiv">
              <h3>Definir responsável</h3>
              <div id="responsibleFormDiv">&nbsp;</div>
				<br class="clear"/>
                <!--<a class="alpha" href="#responsible" id="hideResponsibleHref">Esconder</a>-->
				<a class="button" href="javascript:closeResponsibleDiv();" id="hideResponsibleHref">Esconder</a>
              </div>
          </div>

