<?php
  $pageData = $this->pageData;
?>
        <div id="MainHeader">
          <h1><?php print($this->translate('#Project')) ?> <?php print($pageData['projectTitle']) ?></h1>
        </div>
        <div class="TituloForm">
          <h2><?php print($this->translate('#New team member for action')) ?> <a href='/projects/action/detail/?id=<?php print($pageData['actionId']) ?>'><?php echo $pageData['actionTitle']; ?></a></h2>
        </div>
<?php echo $this->form; ?>