<!-- header -->
<?php echo $this->action('include', 'header', 'includes') ?>
<!-- /header -->

		<div id="Main" class="sixteen columns">

  		<div class="spacer one column alpha"></div>
      <div id="Stage" class="fourteen columns">
<?php echo $this->layout()->content; ?>
<!-- apendix -->
      <div id="apendix">&nbsp;</div>
<!-- /apendix -->
    		</div><!-- #Stage -->
  		<div class="spacer one column omega"></div>

		</div><!-- #Main -->
