<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="pt-br"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="pt-br"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="pt-br"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="pt-br"> <!--<![endif]-->
<html>
  <head>
    <title><?php echo $this->layout()->title?></title>
    <!-- [# Não está pegando o título ] -->

<?php include ("meta.phtml") ?>

    <meta charset="utf-8">

    <!-- Mobile Specific Metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" type="text/css" href="/css/base.css">
    <link rel="stylesheet" type="text/css" href="/css/skeleton.css">
    <link rel="stylesheet" type="text/css" href="/css/formalize.css">
    <link rel="stylesheet" type="text/css" href="/css/zebra/zebra_style.css">
    <link rel="stylesheet" type="text/css" href="/css/zebra/zebra_datepicker.css">
    <link rel="stylesheet" type="text/css" href="/css/zebra/zebra_dialog.css">

    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Favicons
    ================================================== -->
    <link rel="shortcut icon"    href="/images/favicon.ico">
    <link rel="apple-touch-icon" href="/images/apple-touch-icon.png">
    <link rel="apple-touch-icon" href="/images/apple-touch-icon-72x72.png"   sizes="72x72">
    <link rel="apple-touch-icon" href="/images/apple-touch-icon-114x114.png" sizes="114x114">

    <!-- Javascripts
    ================================================== -->

    <script type="text/javascript" src="/js/jquery.js"></script>
    <script type="text/javascript" src="/js/jquery.formalize.js"></script>
    <script type="text/javascript" src="/js/jquery.meio.mask.js" charset="utf-8" ></script>
    <script type="text/javascript" src="/js/zebra_datepicker.js"></script>
    <script type="text/javascript" src="/js/zebra_dialog.js"></script>
    <script type="text/javascript" src="/js/zebra-configs.js"></script>

    <link rel="stylesheet" type="text/css" href="/css/anylinkcssmenu.css" />
    <script type="text/javascript" src="/js/anylinkcssmenu.js"></script>
    <script type="text/javascript">
      anylinkcssmenu.init("anchorclass")
    </script>

    <link rel="stylesheet" type="text/css" href="/css/datatables.css" />
		<script type="text/javascript" src="/js/jquery.dataTables.js"></script>
		<script type="text/javascript" src="/js/dataTables_init.js"></script>


  	<link href="/css/jquery-wijmo.css" rel="stylesheet" type="text/css" />
  	<link href="/css/jquery.wijmo.wijtabs.css" rel="stylesheet" type="text/css" />

  	<script src="/js/jquery-ui-1.8.23.custom.min.js" type="text/javascript"></script>
  	<script src="/js/jquery.wijmo.wijtabs.js" type="text/javascript"></script>
  	<script type="text/javascript">
  		$(document).ready(function () {
  			$("#tabs").wijtabs();
  		});
  	</script>

    <link rel="stylesheet" type="text/css" href="/css/layout.css">

    <link type="text/css" href="/css/jquery.treeTable.css" rel="stylesheet" />
    <script type='text/javascript' src='/js/persist.js'></script>
    <script type="text/javascript" src="/js/jquery.treeTable.js"></script>
    <script type="text/javascript">
      $(document).ready(function()  {
        $("#tree").treeTable();
          childPrefix       :   "child-of-"   /* Customize the prefix used for node classes. */
          clickableNodeNames: false           /* Set to true to expand branches not only when expander icon is clicked but also when node name is clicked. */
          expandable        : true            /* Should the tree be expandable? An expandable tree contains buttons to make each branch with children collapsable/expandable. */
          indent            : 19              /* The number of pixels that each branch should be indented with. */
          initialState      : "collapsed"     /* Possible values: "expanded" or "collapsed". */
          onNodeShow        : null            /* Callback function fired when a node is made visible. */
          persist           : false           /* Persist tree state on client side (requires persist.js). */
          persistStoreName  : "treeTable"     /* Store name used when persist is true. */
          treeColumn        : 0               /* The number of the column in the table that should be displayed as a tree. */
      });
    </script>

    <!-- Initializing jquery.meio.mask -->
    <script type="text/javascript" charset="utf-8">
      $(document).ready(function() {
        $.mask.masks = $.extend($.mask.masks, {
        });
        $("[alt=phone]").live('keypress', function (event) {
          var target, phone, element;
          target = (event.currentTarget) ? event.currentTarget : event.srcElement;
          phone = target.value.replace(/\D/g, '');
          element = $(target);
          element.unsetMask();
          if (phone.length > 5 && phone.substr(0,3) > "115"   && phone.substr(0,3) <= "119") { //ele só vai colocar no formato de SP quando for ddd 11 e iniciar com 9.
            element.setMask("(99) 999-999-999");
          } else {
            element.setMask("(99) 9999-9999");
          }
        })
        $('input:text').setMask();
      });
    </script>
  </head>
  <body>
    <div class="container" id="Envelope">
<?php
  if ($this->layout()->nestedLayout) {
      $this->layout()->setLayout($this->layout()->nestedLayout);
  } else {
      $this->layout()->setLayout('inner');
  }
  echo $this->layout()->render();
?>
<!-- footer -->
<?php //echo $this->action('inclui', 'footer', 'includes') ?>
<!-- /footer -->
    </div><!-- #Envelope -->
  </body>
</html>