<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<?php include ("meta.phtml") ?>

<link rel="stylesheet" href="/css/styles.css" type="text/css" media="screen"/>
<link rel="stylesheet" href="/css/css3.css" type="text/css" media="screen"/>
<link rel="stylesheet" href="/css/forms.css" type="text/css" media="screen" />

<title><?php echo $this->layout()->title?></title>

<?php
$this->dojo()->setDjConfigOption('usePlainJson',true)
        ->addStylesheetModule('dijit.themes.tundra')
        ->setLocalPath("/js/dojo/dojo/dojo.js");
    
echo $this->dojo();

?>

<?php



//<script src="//ajax.googleapis.com/ajax/libs/dojo/1.7.2/dojo/dojo.js"
//               data-dojo-config="async: true"></script>


?>
</head>

<body class="tundra">
<!-- container -->
<div id="container">
<?php
if ($this->layout()->nestedLayout) {
    $this->layout()->setLayout($this->layout()->nestedLayout);   
} else {
    $this->layout()->setLayout('inner');
}
echo $this->layout()->render();
?>

<!-- footer -->
<?php //echo $this->action('inclui', 'footer', 'includes') ?>
<!-- /footer -->

</div>
<!-- /container -->

</body>
</html>