<?php
  $pageData = $this->pageData;
?>
<?php print($this->translate("#Start confirmed.")); ?>

<div id="acknowledgeReceipt-<?php print($pageData['id']);?>">
    <div class="three columns alpha omega">
    <a class="button full column alpha omega parent_info" href="javascript:acknowledgeReceipt('<?php print($pageData['id']); ?>');"><?php print($this->translate("#Confirm task realization")); ?></a>
    </div>
</div>