        <div id="MainHeader">
          <h1><?php echo $this->translate("#Project") ?> <a href="/projects/project/detail/?id=<?php echo $this->pageData['projectId']; ?>"><?php echo $this->pageData['projectTitle']; ?></a></h1>
        </div>
        <div class="TituloForm">
          <h2><?php echo $this->pageData['actionLabel'] ?></h2>
        </div>
<form id="form" action="<?php echo $this->escape($this->form->getAction()); ?>" method="<?php echo $this->escape($this->form->getMethod()); ?>">
<table>
  <?php echo $this->form->project ?>
  <?php echo $this->form->subordinatedTo ?>
  <?php echo $this->form->title ?>
  <?php echo $this->form->supervisor ?>
  <?php echo $this->form->description ?>
  <?php echo $this->form->baselineBeginDate ?>
  <?php echo $this->form->baselineFinishDate ?>
<?php

    $user = Zend_Registry::get('user');
    $role = $user->GetRole();
    if ($role == C3op_Access_RolesConstants::ROLE_SYSADMIN) {
?>
  <?php echo $this->form->predictedBeginDate ?>
  <?php echo $this->form->predictedFinishDate ?>
  <?php echo $this->form->realBeginDate ?>
  <?php echo $this->form->realFinishDate ?>

<?php
    }


?>


  <?php echo $this->form->submit ?>
</table>
</form>



