<?php
$pageData = $this->pageData;
$actionInfo = $pageData['actionInfo'];
$actionHeader = $pageData['actionHeader'];
$staffList = $pageData['humanResourcesList'];


?>
<?php
if (is_array($actionInfo)) {
  $actionInfo = $actionInfo;
?>
<script type="text/javascript">

function acknowledgeStart(id)
{
    $.ajax({
      type: 'get',
      data: 'id=' + id,
      url:'/projects/action/acknowledge-start',
      success: function(successReturn){
        $('#acknowledgeStart-'+id).html(successReturn);
      }
       })
}
</script>
    <div id="MainHeader">
      <h1><?php print($this->translate("#Project")); ?> <a href="/projects/project/detail/?id=<?php print($actionHeader['projectId']) ?>"><?php print($actionHeader['projectTitle']) ?></a></h1>
      <p>
        <?php print($this->translate("#Details of action ")); ?> <?php print($actionHeader['title']) ?>
      </p>
    </div><!-- MainHeader -->

    <div class="Area">

      <div class="three columns alpha Right">
        Responsável:
      </div>
      <div class="six columns">
        <?php print($actionHeader['responsibleName']); ?>
      </div>
      <div class="two columns Right">
        Status:
      </div>
      <div class="three columns omega">
        <?php print($this->translate($actionHeader['status'])); ?>
      </div>

      <div class="three columns alpha Right">
        Subordinada a:
      </div>
      <div class="eleven columns omega">
        <a class="parent_info" href="/projects/action/detail/?id=<?php print($actionHeader['parentActionId']); ?>"><?php print($actionHeader['parentActionTitle']); ?></a>
      </div>

      <div class="three columns alpha Right">
        Composta por:
      </div>
      <div class="eleven columns omega">


        <table id="SubAcoes" class="display dataTable">
          <thead>
            <tr>
              <th width="five columns alpha omega">Ação</th>
              <th width="three columns alpha omega">Responsável</th>
              <th width="two columns alpha omega">Status</th>
              <th width="1%">&nbsp;</th>
            </tr>
          </thead>
          <tbody>
<?php
$subordinatedTree = $actionHeader['subordinatedTree'];
foreach ($subordinatedTree as $id => $actionData) {
    $nodeId = "node-" . $id;
    $childOf = $actionData['subordinatedTo'];
    if ($childOf > 0) {
        $classId = "\"child-of-node-$childOf\"";
        $classId = 'class = ' . $classId;
    }
?>
            <!-- ### loop de carga das ações subordinadas a esta ação -->
            <tr>
              <td><a href="/projects/action/detail/?id=<?php print($id);?>"><?php print($actionData['title']) ?></a></td>
              <td><?php print($actionData['responsibleName']); ?></td>
              <td><?php print($actionData['status']); ?></td>
                  <td>
                <a href="#" class="button one column alpha omega anchorclass" rel="submenu1">Opções</a>
                <div id="submenu1" class="anylinkcss">
                    <ul>
                      <li>
                        <a href="/projects/action/edit/?id=<?php print($id);?>">Editar</a>
                      </li>
                      <li>
                        <div id='rejectReceipt-<?php print($id);?>'><a class="parent_info" href="<?php print($actionInfo['rejectLink']); ?>">Rejeitar</a></div><br />
                      </li>
                      <li>
                        <div id='acceptReceipt-<?php print($actionHeader['id']);?>'><a class="parent_info" href="<?php print($actionInfo['acceptLink']); ?>">Aceitar</a></div><br />
                      </li>
                    </ul>
                </div><!-- #submenu1 -->
              </td>
            </tr>
            <!-- ### fim do loop de carga das ações subordinadas a esta ação -->
<?php
}
?>
          </tbody>
        </table><br />
      </div>

      <div class="three columns alpha Right">
        Descrição:
      </div>
      <div class="eleven columns omega">
        <?php print($actionHeader['description']); ?>
      </div>

      <div class="three columns alpha Right">
        Início previsto:
      </div>
      <div class="one column">
        <?php print($actionHeader['predictedBeginDate']); ?>
      </div>
      <div class="three columns Right">
        Término previsto:
      </div>
      <div class="one column">
        <?php print($actionHeader['predictedFinishDate']); ?>
      </div>
      <div class="three columns inset-by-three omega">
        <?php print($this->translate($actionHeader['milestone'])); ?>
      </div>

      <div class="three columns alpha Right">
        Início real:
      </div>
      <div class="one column">
        <?php print($actionHeader['realBeginDate']); ?>
      </div>
      <div class="three columns Right">
        Término real:
      </div>
      <div class="one column">
        <?php print($actionHeader['realFinishDate']); ?>
      </div>
      <div class="three columns inset-by-three omega">

<?php
if ($actionHeader['unacknowledgedStart']) {

?>
        <div id='acknowledgeStart-<?php print($actionHeader['id']); ?>'>
          <a class="full column button full column alpha omega" href="javascript:acknowledgeStart('<?php print($actionHeader['id']); ?>');"><?php print($this->translate("#Acknowledge start")); ?></a>
        </div>
<?php
} else {
?>
          &nbsp;
<?php
}
?>
      </div>

      <div class="three columns alpha Right">
        Recebida em:
      </div>
      <div class="one column">
        <?php print($actionHeader['receiptDate']); ?>
      </div>
      <div class="three columns">
        <p>
          <a class="button full column alpha omega parent_info" href="<?php print($actionInfo['rejectLink']); ?>">Rejeitar a tarefa</a>
        </p>
      </div>
      <div class="three columns inset-by-four omega">
        <div id='acceptReceipt-<?php print($actionHeader['id']);?>'>
          <a class="button full column alpha omega parent_info" href="<?php print($actionInfo['acceptLink']); ?>">Aceitar a tarefa</a></div>
      </div>

      <div class="three columns alpha Right">
        Realizada em:
      </div>
      <div class="one column inset-by-ten omega">
        <?php print($actionHeader['doneDate']); ?>
      </div>

    </div><!-- .Area -->

    <div class="Area">

      <h2>Recursos humanos</h2>
      <table id="RecursosHumanos" class="display dataTable">
        <thead>
          <tr>
            <th width="220">Nome</th>
            <th width="80">Papel</th>
            <th width="100">Valor</th>
            <th width="100">Situação</th>
            <th width="100">&nbsp;</th>
          </tr>
        </thead>
        <tbody>

<?php
foreach ($staffList as $id => $staffData) {
?>          <!-- ### loop de carga dos recursos humanos alocados a esta ação -->
          <tr>
            <td>
              <a href="/projects/human-resource/edit/?id=<?php print($id) ?>"><?php print($staffData['name']) ?></a>
            </td>
            <td>
              <?php print($staffData['description']) ?>
            </td>
            <td>
              <?php print($staffData['value']) ?>
            </td>
            <td>
              <?php print($staffData['contractingStatus']) ?>
            </td>
            <td>
              <a href="#" class="button one column alpha omega anchorclass" rel="submenu2">Opções</a>
              <div id="submenu2" class="anylinkcss">
                  <ul>
                    <li>
                      <a href="/projects/human-resource/edit/?id=<?php print($id) ?>">Editar</a>
                    </li>
                    <li>
                      <div id='dismissContact-<?php print($id);?>'><a class="parent_info" href="">dispensar recurso</a></div>
                    </li>
                    <li>
                      <a class="parent_info" href="/projects/human-resource/contract/?id=<?php print($id);?>" >confirmar contratação de recurso</a>
                    </li>
                  </ul>
              </div><!-- #submenu1 -->
            </td>
          </tr>
          <!-- ### fim do loop de carga dos recursos humanos alocados a esta ação -->
<?php
}
?>

        </tbody>
      </table>

      <p>
        <a href="/projects/human-resource/create/?actionId=<?php print($actionInfo['id']); ?>" class="button three columns alpha omega">Prever recurso humano</a>
      </p>

    </div><!-- .Area -->

    <div class="Area">

      <p>
        <a href="<?php print($actionInfo['editLink']) ?>" class="button three columns alpha omega">Editar esta ação</a>
        <a href="/projects/action/create/?subordinatedTo=<?php print($actionHeader['id']) ?>" class="button three columns alpha omega"><?php print($this->translate("#Create new action")) ?></a>
      </p>

    </div><!-- .Area -->

    <!-- ### Será preciso montar a tabela de recursos materias, idêntica à de recursos humanos, assim que forem tratados pelo sistema -->

<?php
}
?>
