<?php
    $pageData = $this->pageData;
?>
<script type="text/javascript">

    function clearSubordinatedToField()
    {
        var $el = $("#subordinatedTo");
        $el.empty();
        $el.append($("<option></option")
            .attr("value", 0)
            .text(<?php echo $this->translate("(A product can\'t be subordinated to other action)"); ?> ));
        $el.prop('disabled', true);
    }

    function populateSubordinatedToField() {
        var id = $('#id').val();
        var $el = $("#subordinatedTo");

        $.getJSON('/projects/action/populate-subordinated-to/?id=' + id, function(data) {
        var html = '';
        var len = data.length;
        html += '<option value="0">(nenhuma ação)</option>';
        for (var i = 0; i< len; i++) {
            html += '<option value="' + data[i].id + '">' + data[i].title + '</option>';
        }
        $el.empty();
        $el.append(html);
        $el.prop('disabled', false);
        });
    }


$( document ).ready(function() {

        var $p = $("#product");
        var $sT = $("#subordinatedTo");

        if ($p.is(':checked')) {
            clearSubordinatedToField();
        }

    $('#product').click(function(){
        if (this.checked) {      //this.checked is NOT from jquery
            clearSubordinatedToField();
        } else {
            populateSubordinatedToField();
        }
    });




});


</script>



<div id="MainHeader">
          <h1><?php echo $this->translate("#Project") ?> <a href="<?php echo $this->linkProjectDetail; ?>"><?php echo $this->projectTitle; ?></a></h1>
        </div>
        <div class="TituloForm">
          <h2><?php echo $this->translate("#Edit action") ?></h2>
        </div>
<form id="form" action="<?php echo $this->escape($this->form->getAction()); ?>" method="<?php echo $this->escape($this->form->getMethod()); ?>">
<table>
  <?php echo $this->form->id ?>
  <?php echo $this->form->project ?>
  <?php echo $this->form->subordinatedTo ?>
  <?php echo $this->form->title ?>
  <?php echo $this->form->supervisor ?>
  <?php echo $this->form->description ?>
<?php
    if ($pageData['showBaseline']) {
?>
  <?php echo $this->form->baselineBeginDate ?>
  <?php echo $this->form->baselineFinishDate ?>
<?php
    }
?>
<?php

    if ($pageData['showPredicted']) {
?>
  <?php echo $this->form->predictedBeginDate ?>
  <?php echo $this->form->predictedFinishDate ?>
<?php
    }
?>
<?php

    if ($pageData['showReal']) {
?>
  <?php echo $this->form->realBeginDate ?>
  <?php echo $this->form->realFinishDate ?>

<?php
    }
?>
<?php
    if ($pageData['showStatus']) {
?>
  <?php echo $this->form->status ?>
<?php
    }
?>
  <?php echo $this->form->submit ?>
</table>
</form>

